- config/deploy.rb
This PR use the new github repo, *without* changing the application name.
> update deploy scripties to new github repo

- .travis.yml
- README.md
- spec/spec_helper.rb
An empty commit wasn't enough to kick travis.org into action. Needed some extra whitespace in there.
> Check travis

- script/fix_visibility_nil.rb
Fixes https://github.com/sul-dlss/sul-pub/issues/500. Would need to be run in production (`rails runner script/fix_visibility_nil.rb`)
> fix cases where Author still has contributions with visibility.nil? == true

- LICENSE
> add a license to the project

- script/fix_visibility_nil.rb
This PR fixes #68. Needs to be run in production.
> add scriptie that fixes authors missed by cap:poll

- lib/science_wire/harvest_broker.rb
> SW-HarvestBroker - needs to explicitly instantiate an SW-AuthorName

- lib/science_wire/harvest_broker.rb
- spec/integration/harvest_broker_spec.rb
Revised the seeds method so the code/specs are consistent and added a spec for the seeds method.
> SW-HarvestBroker - seeds calls author.approved_sciencewire_ids

- Capfile
- Gemfile
- Gemfile.lock
- Rakefile
- app/controllers/application_controller.rb
- app/jobs/author_harvest_job.rb
- config/deploy.rb
- config/initializers/squash.rb
- config/settings.yml
- lib/notification_manager.rb
- spec/lib/notification_manager_spec.rb
> Replace squash with honeybadger and simplify exception reporting

- lib/tasks/pubmed.rake
* move exception handling check to the publication update so that a single publication update failure does not block all other pubs from that author
> updates to pubmed update rake task

- lib/science_wire/author_address.rb
- lib/science_wire/author_attributes.rb
- lib/science_wire/author_institution.rb
- lib/science_wire/author_name.rb
- lib/science_wire/client.rb
- lib/science_wire/query/publication_query_by_author_name.rb
- lib/science_wire/query/suggestion.rb
Incorporates latest `cleanup` branch. Will rebase if #212 gets merged.
Might not matter, but I can chip away at some logical stuff while reading for comprehension.
> More cleanup, now of the sciencewire stuff itself

- .travis.yml
- Gemfile
- Gemfile.lock
Get specs passing on ruby 2.4.x
> [WIP] Ruby 2.4.x

- Gemfile
- Gemfile.lock
- lib/cap_authors_poller.rb
- spec/lib/science_wire_harvester_spec.rb
- spec/spec_helper.rb
These changes address the Fixnum deprecation
- update grape
- `s/Fixnum/Integer/` in a few places
> Ruby 2.4.x additions

- app/controllers/publications_controller.rb
- app/models/author.rb
- app/models/publication.rb
- app/models/pubmed_source_record.rb
- lib/science_wire/harvest_broker.rb
Use active record for good, not evil.
> Less callback hell

- lib/tasks/sw.rake
Based only on author name (string) and default institution.
Fixes #213 
Relies on questionable workaround of matching ScienceWire IDs out of the local database via `publication_identifiers` table.  See https://github.com/sul-dlss/sul_pub/issues/213#issuecomment-335643165 for why that is problematic.
Output is like:
```bash
$ rake sw:wos_publications_for_name[Mangiafico,Peter,A]
Querying ScienceWire for #<ScienceWire::AuthorName:0x007fcc2decbcc8 @last="Mangiafico", @first="Peter", @middle="A">
... [List of SW IDs]
Querying WebOfScience for Mangiafico,Peter,A
... [List of WoS IDs]
0 ScienceWire IDs
0 WebOfScience IDs
0 MEDLINE IDs: 0 of 0 matching PubIDs in DB have SW ID
0 WOS IDs: 0 of 0 matching PubIDs in DB have SW ID
Total INTERSECTION of ScienceWire IDs (0)
0 MEDLINE
0 WOS
Unmatched …
```
> Rake task for comparison of ScienceWire vs. WoS results

- lib/tasks/sw.rake
More counts and an extra newline character.
> Last little tweak to task

- app/models/web_of_science_source_record.rb
- db/migrate/20171010223256_create_web_of_science_source_records.rb
- db/schema.rb
- spec/models/web_of_science_source_record_spec.rb
> WebOfScienceSourceRecord creation

- Gemfile
- Gemfile.lock
> Revert "Bump grape from 0.19.2 to 1.0.1"

- app/models/publication.rb
Small change extracted from work on #246
> Publication - rubocop conversion from unless-blank to if-present

- .gitignore
- Gemfile
- Gemfile.lock
Also ignore the history file created by `byebug`.
> Add byebug for dev debugging

- lib/clarivate/links_client.rb
> Clarivate::LinksClient - allow more than 50 ids

- app/models/contribution.rb
- spec/models/contribution_spec.rb
> Remove unused class method on Contribution

- spec/models/publication_spec.rb
At least where it matters (to possibly adding rails validations).  Split off from #334.
> Use valid status values in tests

- app/models/publication.rb
- lib/tasks/cap_cutover.rake
- spec/api/sul_bib/sourcelookup_spec.rb
- spec/lib/doi_search_spec.rb
- spec/models/publication_spec.rb
> Revert "Publication model has methods that should be private"

- script/publication_identifier_normalization.rb
> Revert "Avoid reloading twice"

- app/models/publication.rb
- app/models/publication_identifier.rb
- spec/factories/publication_identifier.rb
- spec/models/publication_identifier_spec.rb
@atz - split this out of the normalizer PR #384 for easier review.  The work in #384 now depends on this and should be rebased when this is done.
> PublicationIdentifier pubhash methods

- config/initializers/paper_trail.rb
> Reinstall paper_trail after 4.x -> 8.x upgrade

- db/migrate/20171116185807_web_of_science_source_record_ids.rb
- db/schema.rb
> WebOfScienceSourceRecord - migration to add DOI and PMID fields

- lib/web_of_science/identifiers.rb
- lib/web_of_science/record.rb
- spec/lib/web_of_science/identifiers_spec.rb
Fix #410 
Fix #430 
Extracted from #379 for easier review.
> Wos identifiers enhanced

- lib/wos.rb
- spec/lib/wos_spec.rb
Connected to #195 
This adds the `WOS.harvester` utility for console and rake tasks.
> WOS.harvester utility

- lib/notification_manager.rb
- lib/tasks/wos.rake
- lib/web_of_science.rb
- lib/web_of_science/client.rb
- lib/web_of_science/harvester.rb
- lib/web_of_science/process_records.rb
- lib/web_of_science/record.rb
- spec/lib/notification_manager_spec.rb
- spec/lib/web_of_science/client_spec.rb
- spec/lib/web_of_science_spec.rb
Split off from #456 (without the filtering implementation).
> Wos logging

- lib/tasks/wos.rake
- lib/web_of_science/harvester.rb
- spec/lib/web_of_science/harvester_spec.rb
> Rake task to harvest from WebOfScience

- config/settings.yml
> Harvesters ENABLED by settings

- lib/web_of_science/map_mesh.rb
- lib/web_of_science/map_pub_hash.rb
- spec/fixtures/wos_client/medline_record_26776186.xml
- spec/lib/web_of_science/map_mesh_spec.rb
- spec/lib/web_of_science/map_pub_hash_spec.rb
> WebOfScience::MapMesh

- spec/api/sul_bib/authorship_api_spec.rb
All the same tests, 119 fewer lines.
- Suppress copy-pasta.
- Use common `let` statements.
- Use `include` w/ multiple params
- Remove unneeded single-use or redundant `let` statements
- Remove unneeded intermediate variables
- replace `.where(...).first` with `find_by(...)`
- Use `a_hash_including` matcher to replace multiple hash interrogations
- Don't need to check `.not_to be_nil` first before checking `include`
The latter implies the former.
> Moderate cleanup of authorship_api_spec

- config/initializers/okcomputer.rb
- lib/web_of_science/queries.rb
- spec/lib/web_of_science/queries_spec.rb
Fix #196 
Exceptions trigger more informative failure messages in https://github.com/sul-dlss/sul_pub/blob/master/config/initializers/okcomputer.rb#L28
> WebOfScience::Queries.working? for OK computer checks

- lib/tasks/cleanup.rake
- spec/tasks/cleanup_rake_spec.rb
used when there are two known duplicate author rows that refer to the same person
> add a rake task that will merge publications from one author into another

- app/api/sul_bib/authorship_api.rb
- spec/api/sul_bib/authorship_api_spec.rb
Fix #509 
Continuation of spec cleanup, then added Grape param coercion w/ tests.
> Authorship api coerce params

- db/migrate/20171207233451_add_wosuid_to_publication.rb
- db/schema.rb
> Migration adding `wos_uid` field to publications table

- fixtures/vcr_cassettes/WebOfScience_ProcessRecords/with_WOS_records/behaves_like_execute/creates_Publications_with_WOS_attributes.yml
- lib/web_of_science/process_records.rb
- spec/lib/web_of_science/process_records_spec.rb
> WebOfScience::ProcessRecords - assign Publication#wos_uid attribute

- config/initializers/okcomputer.rb
> Tailor OKComputer checks to enabled clients only.

- app/models/publication.rb
- spec/models/publication_spec.rb
> for_uid: use one DB query instead of two

- lib/web_of_science/harvester.rb
- spec/lib/web_of_science/harvester_spec.rb
> WebOfScience::Harvester - use WebOfScience.queries singleton

- lib/web_of_science/harvester.rb
Extracted from #583 
This provides more useful log information when debugging the WOS harvester for authors.
> WebOfScience::Harvester - log progress for author harvests

- Gemfile
- Gemfile.lock
CI not running tests defeats the purpose of CI.
> Rspec is a required gem in both test and devlopment.

- .rubocop.yml
- app/api/sul_bib/authorship_api.rb
- app/models/publication.rb
- spec/api/sul_bib/authorship_api_spec.rb
> Fix #503: remove find_or_create_by_sciencewire_id

- lib/csl/bibtex_mapper.rb
- lib/csl/mapper.rb
Split out of #512 as a bite-sized review chunk
> Csl::Mapper - extract class Csl::BibtexMapper

- lib/pubmed_harvester.rb
- Booleans, how do they work?
- No need to use `map!` on a variable and then return it.  Just return the
result of `map`.
- use `||=` instead of `unless` clauses
- various parens and syntactic cleanup
- Use a ternary instead of conditional assignment and failover
> pubmed_harvester refactoring

- app/views/pages/pollapi.html.erb
Also correct un-encoded ampersands in HTML.
> Update static API docs to reflect current reality.

- app/controllers/publications_controller.rb
The debug logging lines are already reproduced at the `info` level at the top of the `index` method.
Also replace a `.where(...).first` with `find_by(...)`.
> Remove redundant debug logging

- spec/api/sul_bib/sourcelookup_spec.rb
There are no POSTs to sourcelookup anyway!
> Remove unused copy/pasta `let` statement

- lib/web_of_science/process_records.rb
Extracted from #644 - trivial alphabetical reordering of methods
> WebOfScience::ProcessRecords - reorder private methods

- .rubocop.yml
- .rubocop_todo.yml
- app/controllers/publications_controller.rb
- app/models/user_submitted_source_record.rb
- lib/web_of_science/queries.rb
- spec/api/sul_bib/sourcelookup_spec.rb
- spec/controllers/publications_controller_spec.rb
Looks bigger than it really is, but I can break off pieces if necessary.
Conflict in the `rubocop_todo.yml` counts are 100% unimportant.
> Pub controller conversion

- Gemfile
- Gemfile.lock
- script/wos_harvest_profiling.rb
> WOS harvest profiling

- lib/cap/authors_poller.rb
- spec/lib/cap/authors_poller_spec.rb
> skip SW harvest in cap poller when not enabled

- config/initializers/okcomputer.rb
> Add WOS harvest check for records touched w/in 3 weeks

- lib/tasks/wos.rake
- lib/web_of_science/harvester.rb
> WOS rake task to harvest one author

- lib/harvester/base.rb
- spec/lib/harvester/base_spec.rb
Small PR to add logging progress of authors harvested.
- use a relation for the query
- progress is logged at the completion of each batch
> WOS harvest progress

- app/jobs/author_harvest_job.rb
- spec/factories/author.rb
- spec/jobs/author_harvest_job_spec.rb
- spec/lib/web_of_science/contributions_spec.rb
- spec/lib/web_of_science/harvester_spec.rb
- spec/lib/web_of_science/process_record_spec.rb
- spec/lib/web_of_science/process_records_spec.rb
Fix #639 
- added active job specs
- consolidated common author details into a factory
- extract method refactor for the sciencewire harvest
- use settings to enable/disable it
- add harvest method for the WOS harvester
- extract method refactor for logging publication info
> WOS harvest job

- lib/web_of_science/harvester.rb
Split out of #696 
Simple revisions to log details.
> WebOfScience::Harvester - revise logging messages

- app/models/publication.rb
- lib/web_of_science/contributions.rb
- lib/web_of_science/process_record.rb
- lib/web_of_science/process_records.rb
- spec/models/publication_spec.rb
This reduces the duplication of logic.  I will follow up by converting the 4x queries to a single query.
> Consolidation and cleanup around `contribution_by_identifier?`

- db/migrate/20180201233754_remove_xml_from_publication.rb
- db/schema.rb
> Drop empty `xml` field from publications table

- config/initializers/okcomputer.rb
- fixtures/vcr_cassettes/Clarivate_LinksClient/_working_/success/returns_true_when_it_works_has_2_results_.yml
- lib/clarivate/links_client.rb
- spec/lib/clarivate/links_client_spec.rb
> add an ok computer check for the Links AMR client

- fixtures/vcr_cassettes/Cap_Client/_working_/returns_true_when_it_can_fetch_author_data.yml
- lib/cap/client.rb
darren hardy doesn't work here anymore and the previous ID would start failing when we go to -prod
> update cap_profile_id checked since previous referenced a no longer active cap profile

- lib/web_of_science/map_pub_hash.rb
- lib/web_of_science/record.rb
- lib/web_of_science/xml_parser.rb
- spec/lib/web_of_science/map_pub_hash_spec.rb
> Inproceeding detection

- lib/web_of_science/map_citation.rb
- spec/lib/web_of_science/map_citation_spec.rb
> Journal identifier data structure

- app/models/author.rb
- spec/models/author_spec.rb
Including the removal of the last method `def` inside an ActiveRecord callback!
> Remove placeholder methods and unused cruft

- lib/tasks/wos.rake
Exection is like:
```ruby
rake wos:assign_uids[98765] < input.txt
```
With output like:
```
Reading WosUIDs from STDIN...
10 UIDs to assign to Author 496 (cap_profile_id: 98765)
10 newly associated Contributions
```
Closes #479
> Rake task to assign explicit WOSUIDs to an author

- app/models/publication.rb
- app/models/web_of_science_source_record.rb
- db/migrate/20180309022340_add_unique_constraint_to_publication_wosuid.rb
- db/migrate/20180309235252_add_publication_ref_to_web_of_science_source_record.rb
- db/schema.rb
- spec/models/publication_spec.rb
- spec/models/web_of_science_source_record_spec.rb
> Source record linkage

- app/models/author.rb
> cap authors poller exception when creating an author

- config/initializers/okcomputer.rb
> fixed delayed job ok computer check

- lib/web_of_science/process_records.rb
> Prevent a second WoS Source Record from trying to link to the same Pub

- config/settings.yml
- lib/agent/author_name.rb
- spec/lib/agent/author_name_spec.rb
- spec/lib/science_wire/query/publication_query_by_author_name_spec.rb
> create setting for determining whether first name variant is included in name queries

- app/models/pubmed_source_record.rb
- spec/factories/pubmed_source_records.rb
- spec/fixtures/pubmed/pubmed_record_29279863.xml
- spec/models/pubmed_source_record_spec.rb
> parse the year from another spot in the pubmed source record if missing in the first place

- app/models/author_identity.rb
- spec/models/author_identity_spec.rb
> set default first name in alternate identities when missing

- config/settings.yml
Want to validate with Tina first
> update default author harvest settings to nightly author poller

- lib/web_of_science/query_author.rb
- spec/lib/web_of_science/query_author_spec.rb
> remove quotes from names when making names query

- app/models/publication.rb
- app/models/web_of_science_source_record.rb
- lib/web_of_science/process_pubmed.rb
> when assigning contributions, do not save the pub if its not needed

- config/schedule.rb
- config/settings.yml
- lib/harvester/base.rb
- spec/lib/harvester/base_spec.rb
> log enhancements for a complete harvest job

- .travis.yml
2.5.3 now deployed to stage and prod.
> Remove old version of ruby

- Gemfile
- Gemfile.lock
security fix for CVE-2019-5418
> dependency-update

- lib/tasks/sul.rake
sometimes useful for sending data to stakeholders in a useful format
> add a rake task for exporting publications as csv

- config/initializers/okcomputer.rb
potentially useful when debugging to see when the app was last deployed easily in the status check area
> show last deploy time in revision check of okcomputer

- lib/pubmed/query_author.rb
- spec/lib/pubmed/query_author_spec.rb
fixes #1063 by just blunt force changing & to and everywhere with no other variants
> ensure all & is stipped from pubmed queries

- app/models/publication.rb
- spec/models/publication_spec.rb
> Switched uniq to distinct.

- app/controllers/publications_controller.rb
- spec/controllers/publications_controller_spec.rb
> when running manual publication searches, only search the main WOS database

- lib/pubmed/query_author.rb
- spec/lib/pubmed/query_author_spec.rb
> switch pubmed query to last, first instead of last first to avoid false positivies

- config/schedule.rb
> disable all cron jobs on both dev servers

- Gemfile
- Gemfile.lock
- config/routes.rb
Remove the unused rails_db gem (https://github.com/igorkasyanchuk/rails_db), which is now causing problems with the build.
> remove unused railsdb gem to fix build

- lib/cap/profile_id_rewriter.rb
some work possibly coming before the end of the year that may need to make use of this deprecated class
improve some of the notes based on a quick analysis
> add better documentation and notes to a rake task we may need to revive in future

- lib/tasks/sul.rake
- export rake task for Wu Tsai Institute (instead of RIALTO data) ... also is useful in other cases (e.g. for exporting data to be used by Yewno experiments)
- lookup times cited rake task using WOS and Links AMR APIs  given a list of DOIs for Precourt Energy Institute
> add script for exporting pubs for specific sunets

- Gemfile
- Gemfile.lock
Keep dependencies up to date.
no
no
If so, please confirm change was tested on stage and/or test added to sul-dlss/infrastructure-integration-test.
> Upgrade mysql2 to 0.5.3

- .travis.yml
- Gemfile.lock
Maintenance. Keep dependencies up to date.
no
no
If so, please confirm change was tested on stage and/or test added to sul-dlss/infrastructure-integration-test.
> upgrade to bundler2

- Gemfile
- Gemfile.lock
OKComputer has been fixed and Rack needs to be updated due to security vulnerability.
Stage
No
> Unpinned rack

- app/controllers/authorships_controller.rb
- lib/web_of_science/process_records.rb
- lib/web_of_science/record.rb
- spec/controllers/authorships_controller_spec.rb
- spec/lib/web_of_science/process_records_spec.rb
Fixes #1198
Test suite and manually on sul-cap-dev
None
> do a better job of finding existing matching publication records when adding then manually

- lib/smci_report.rb
- lib/tasks/sul.rake
- spec/factories/author.rb
- spec/fixtures/reports/input.csv
- spec/lib/smci_report_spec.rb
Fixes #1201 
A specific custom report that combines publications from our database with WoS name queries for people not in our database.
Running the report on my laptop with various iterations of data.  New unit test to verify basic runnability.
None yet, but will add to the wiki.
> add new custom report

- bin/faculty_wos_search.rb
- bin/totals_wos_search.rb
Scripts that are useful for collating data directly from WoS (bypassing rialto)
> Rialto like search of WoS data

- README.md
- config/deploy.rb
> Update reference from master to main

- lib/tasks/sul.rake
This is a new rake task that allows us to dump author information for a given list of authors.  It is being used in an analysis for comparing WoS queries against other sources (like Dimensions) to ensure we can run the same queries using exactly the same parameters when doing comparison analysis.
Localhost browser.
> add a report for exporting author information with identities

- app/models/author.rb
try to get rid of rubocop exception and make things slightly more readable
existing unit tests
n/a
> refactor Author#unique_first_initial? logic into slightly smaller helper methods

- README.md
Goes with a proposed change in #1278 about cleaning up of shared_configs
> updates to readme on shared configs

- .circleci/config.yml
removing a line of cruft leftover from when i was iterating on https://github.com/sul-dlss/sul_pub/pull/1286
CI
circle CI config
> remove CI config cruft

- lib/tasks/sul.rake
Fixes #1291 -- get sample publication data in pub_hash/json format
Note: i tried to use `order('RAND()')` to get a random set each time but this was seriously non-optimal with lots of rows and cause disk space issues on the dev server, decided it wasn't worth the effort to worry about a random selection
on `sul-pub-cap-dev-a`
> add a rake task to export publication pub_hashes

- .rubocop.yml
Love the rubocops.
Unit
`.rubocop.yml`
> Enable new cops.

- lib/tasks/sul.rake
* Allow random sampling.
* Pretty print JSON.
Dev
NA
> Tweaks to export_pubs_json rake task.

- fixtures/vcr_cassettes/Orcid_Client/_fetch_work/retrieves_work.yml
- lib/orcid.rb
- lib/orcid/client.rb
- spec/lib/orcid/client_spec.rb
- spec/lib/orcid_spec.rb
closes #1290
It will be used to populate the publication.
Unit
NA
> Adds fetching work details to Orcid client.

- README.md
Had to generate some vcr cassettes and some setup was missing.  Documented in the README.
> updates to readme regarding vcr casssette generation

- config/settings.yml
- db/migrate/20210519134457_add_put_code_to_contribution.rb
- db/schema.rb
- lib/notification_manager.rb
- lib/orcid.rb
- lib/orcid/add_works.rb
- lib/orcid/identifier_type_mapper.rb
- lib/orcid/pub_mapper.rb
- lib/tasks/orcid.rake
- spec/lib/orcid/add_works_spec.rb
- spec/lib/orcid/identifier_type_mapper_spec.rb
- spec/lib/orcid/pub_mapper_spec.rb
Note: hold for testing on cap-dev-a
closes #1261
Support adding publications to ORCID.org for an author.
Sandbox/locally, unit
NA
> [HOLD] Adds task for adding works to ORCID.org.

- lib/orcid/identifier_type_mapper.rb
- spec/lib/orcid/identifier_type_mapper_spec.rb
To match Arcadia's specs.
Unit
NA
> Tweak to identifier type mapping.

- README.md
Make it easier to find wiki docs.
NA
README
> Added wiki link.

- lib/orcid/delete_works.rb
- lib/tasks/orcid.rake
- spec/lib/orcid/client_spec.rb
- spec/lib/orcid/delete_works_spec.rb
easy touchups for suggestions made when reviewing #1346.  tried to lump them in commits ordered from what i thought would be least to most controversial, in case any of the changes were undesired.
unit
n/a
> tweaks to deleting orcid works

- fixtures/vcr_cassettes/Orcid_Client/_delete_work/deletes_work.yml
- fixtures/vcr_cassettes/Orcid_Client/_delete_work/returns_true.yml
- lib/orcid/client.rb
- lib/orcid/delete_works.rb
- lib/tasks/orcid.rake
- spec/lib/orcid/client_spec.rb
- spec/lib/orcid/delete_works_spec.rb
closes #1345
It is our destiny to need to delete works from Orcid.
Unit, cap-qa
NA
> Adds support for deleting works from Orcid.

- config/database.yml
- docker-compose.yml
This parallels how we have the database set up for testing on circleci.
> Simplify the docker database setup

- lib/tasks/sul.rake
Small change to ORCID output report rake task to break down name into first and last name columns.
Localhost
> output first and last names in orcid report

- lib/tasks/sul.rake
More research intelligence related work, helpful for running some custom reports.
Localhost and prod
> add a rake task for looking up sunets given a full name

- lib/tasks/sul.rake
Fixes #1437 - for reporting out to research intelligence group - some monthly usage stats
UAT server
> add a rake task for monthly stats reporting

- lib/tasks/sul.rake
We need to provide monthly stats on the number of ORCID users who have integrated with Stanford.  This wraps up the queries into an easy to run rake task.
UAT and localhost
Updated the wiki page and google doc where results are stored
> add a rake task to produce latest orcid integration stats

- lib/tasks/sul.rake
Based on a research intelligence meeting where results were discussed, we changed some header language and how some percents are computed by the rake task.
UAT server
> small tweak to how percents are computed for stats report

- .rubocop.yml
- spec/lib/mais/update_authors_orcid_spec.rb
- spec/lib/orcid/harvester_spec.rb
- spec/lib/orcid/pub_mapper_spec.rb
- spec/lib/web_of_science/harvester_spec.rb
- spec/models/author_identity_spec.rb
- spec/models/author_spec.rb
- spec/tasks/cleanup_rake_spec.rb
Add new cops and run auto-correct
Tests
> add new cops and autocorrect

- README.md
Follow on from #1461 - update readme
> update readme to reflect change in database usage

- .rubocop.yml
> add new cops to config

- config/initializers/okcomputer.rb
This gives us an okcomputer endpoint to hit that includes all checks we might want to alert about, not the ones that trigger partner email. Helps with Nagios integration.
Tested in cap-dev env.
> Create a critical checks endpoint for okcomputer

- .rubocop.yml
- lib/orcid/pub_author_mapper.rb
To fix rubocop error.  Also add new configs.
Existing tests.
> rubocop fix, plus new rubocop config

- lib/tasks/sul.rake
For reporting purposes - update the rake task for author export to add orcidid (and alternate identities in csv format)
Running the report in production
> update author report to add orcidids

- .rubocop.yml
- lib/tasks/sul.rake
Add new rubocop styles and auto-correct
Existing tests
> add new rubocop styles and auto-correct

- .rubocop.yml
Add new cop (no changes needed).
> add new cop to config

- .rubocop.yml
> add new cop

- config/settings.yml
> we are not using this config anymore

- .rubocop.yml
- lib/tasks/cleanup.rake
- spec/lib/orcid/add_works_spec.rb
Add new rubocop config and correct
Existing tests
> add new rubocop config and correct

- config/application.rb
For better understanding of why the configuration is set as it is.
> Add a comment about which column required permitted YAML parameters

- app/helpers/application_helper.rb
> Remove unused method

- Capfile
Deploy was missing assets:precompile rake task. So we changed some
things.
We deployed it to QA!
> Capfile changes

- config/application.rb
Also allow for Hashie::Array serialization in YAML.
Fixes #1534
CI
> Allow Hashie::Array in YAML

- lib/tasks/sul.rake
When exporting ORCID users for use in research intelligence reporting, we may want to just get the list of users known to sul-pub who have been through the Stanford integration, without also querying for read/wrote scope or querying the ORCID API for other potential Stanford researchers who have not been through the Stanford integration.  Both of these other queries require iterating over many results and issuing lots of API calls, and they are time consuming, while just getting a list of users with known ORCIDs is fast.
This changes the rake task to that you can specify if you want the time consuming parts to really run (the both default to false here and will be skipped).
On UAT.
> provide options for orcid export rake task

- .rubocop.yml
- spec/controllers/authorships_controller_spec.rb
- spec/lib/orcid/harvester_spec.rb
- spec/lib/web_of_science/process_records_spec.rb
- spec/models/author_spec.rb
- spec/models/publication_spec.rb
- spec/models/web_of_science_source_record_spec.rb
- spec/tasks/cleanup_rake_spec.rb
Enable new cops and autocorrect errors.
> Enable new cops

- Gemfile
> Gemfile: factory-bot-rails pin gets info on when to unpin

- .circleci/config.yml
- .rubocop.yml
> Bump Ruby to 3.3.1

- .rubocop.yml
- lib/cap/authors_poller.rb
- lib/pubmed/map_pub_hash.rb
- lib/smci_report.rb
- lib/web_of_science/map_abstract.rb
- lib/web_of_science/map_mesh.rb
- lib/web_of_science/map_names.rb
- lib/web_of_science/map_publisher.rb
- script/batch_wos_harvest.rb
saw some rubocop rules to add when i was touching up #1721 for weekly dep updates
existing unit tests
`.rubocop.yml`
> add missing rubocop rules, make suggested corrections

- Gemfile
- Gemfile.lock
> Clarify dependency on mutex_m

- lib/tasks/sul.rake
Fixes #1768
Localhost, returned valid results
> speed up orcid integration stats rake task by avoiding many API calls

- Gemfile
- Gemfile.lock
- config/initializers/mais_orcid_client.rb
- config/settings.yml
Part of https://github.com/sul-dlss/dor-services-app/issues/5284
Has shared_configs updates too (linked to from ticket above)
~~Waiting on testing switchover~~
> Update mais-orcid-client gem

- Gemfile
- Gemfile.lock
> pin rails to 8.0.0
