script/fix_sw_procs_marked_as_article.rb
This PR is connected to #23. For #23 the fixit scriptie is wrong. It needs to rebuild the `publications.pub_hash` from the `SciencewireSourceRecord` data. 
Note that this scriptie will generate exceptions until #77 is fixed.
=> rebuild pub_hash entirely

Rakefile
=> workaround Rails.env being sent in default squash:notify task

spec/lib/science_wire/harvest_broker_spec.rb
Connected to #97 (but not a complete fix because it does not test all the private methods).
=> SW-HarvestBroker - add specs for some private methods

spec/spec_helper.rb
This PR fixes #81. https://coveralls.io/github/sul-dlss/sul_pub has activity now.
=> fix Coveralls by changing repo name and using Coveralls formatter

lib/cap_authors_poller.rb, spec/lib/cap_authors_poller_spec.rb
=> use valid_fields? only to check on CAP authorship attached to profile

app/models/pubmed_source_record.rb, spec/models/pubmed_source_record_spec.rb
This PR fixes #74. I've made the assumption that if `ValidYN` is *missing* then we should ignore it.
=> handle case of missing ValidYN attribute

app/models/publication.rb, app/models/pubmed_source_record.rb, app/models/sciencewire_source_record.rb, fixtures/vcr_cassettes/SciencewireSourceRecord/instance_methods/_sciencewire_update/updates_the_is_active_field.yml, fixtures/vcr_cassettes/SciencewireSourceRecord/instance_methods/_sciencewire_update/updates_the_pmid_field.yml, fixtures/vcr_cassettes/SciencewireSourceRecord/instance_methods/_sciencewire_update/updates_the_source_data_field.yml, fixtures/vcr_cassettes/SciencewireSourceRecord/instance_methods/_sciencewire_update/updates_the_source_fingerprint_field.yml, script/missing_wos_ids.rb, spec/models/sciencewire_source_record_spec.rb
This script will log some details for all the ScienceWire publications with a missing WoSItemID.  On a prod-db-dump, all of the identified publications did not have a WoSItemID in the ScienceWireSourceRecord.  No attempt is made to re-harvest the publications; if that is a requirement, it can be added, but that will be extra work to change this script from a read-only operation into an update operation.
This should fix #86
=> 86 missing wos ids

config/deploy/cap-qa.rb, config/deploy/production.rb, config/schedule.rb, lib/tasks/sul.rake
Added a new rake task that calls the external okcomputer checks for a given URL.  Added a new role for the whenever gem that schedules this task every 30 minutes in cap-qa and production.
If an exception occurs during the checks, a honeybader notification will be sent out (this is already working in the code). 
With this, we can remove the nagios alerts for these three external checks.
Note I shelled out to 'hostname' to get the URL to check.  Since cap-qa and prod both run under Rails.env == production, you can't use a hostname that is configured in the Rails app.  I also couldn't find a way to pass a value from the cap script to the schedule.rb file.
fixes #119
=> set up a scheduled rake task for performing external monitor checks

lib/tasks/pubmed.rake
given a list of PMIDs and cap profile id
Useful when I need to batch import pubs for a new faculty member.  There is an existing similar rake task for doing this by WoSID, but sometimes there are pubs that only exist in PubMed and not yet in Web of Science
=> add new rake task to bulk import a list of publications

app/models/publication.rb, app/models/pubmed_source_record.rb, spec/models/publication_spec.rb
Add PMC identifiers to pub_hash from pubmed source record when available.
Need to also rebuild all pub hashes
=> Add pmc ID to pub hash

.rubocop_todo.yml, app/models/publication.rb, app/models/pubmed_source_record.rb, lib/tasks/pubmed.rake, lib/tasks/sul.rake, spec/models/publication_spec.rb, spec/models/pubmed_source_record_spec.rb
also add a rake task to repull all pubmed records for given cap_profile_ids and then update the pub_hash
This is useful to refresh PMID based publications (for example, when we need to be sure we add PMCIDs to our source records where they have been added to PubMed after we first pulled)
=> add a new method to repull pubmed record so we can update our source

.travis.yml, Gemfile.lock
Taking a more incremental approach.
This was necessary to avoid an error during `bundle install`:
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory: /Users/atz/.rvm/gems/ruby-2.3.4/gems/libv8-3.16.14.13/ext/libv8
/Users/atz/.rvm/rubies/ruby-2.3.4/bin/ruby -r ./siteconf20170918-69253-y4hiue.rb extconf.rb
creating Makefile
Compiling v8 for x64
Using python 2.7.13
Using compiler: /usr/bin/c++ (clang version 7.3.0)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/atz/.rvm/gems/ruby-2.3.4/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o has no symbols
In file included from ../src/accessors.cc:28:
In file included from ../src/v8.h:60:
In …
```
=> update libv8 slightly

Gemfile, Gemfile.lock, config/settings.yml, lib/wos_client.rb, spec/fixtures/wos_client/authenticate.xml, spec/lib/wos_client_spec.rb
This explores using the ruby savon gem for SOAP.
- it can authenticate to the new SOAP API for Web of Science
- it initializes a search SOAP client
Use in `rails c`
```ruby
[2] pry(main)> wos = WosClient.new(Settings.WOS.AUTH_CODE);
I, [2017-09-27T08:58:32.938193 #12354]  INFO -- : SOAP request: http://search.webofknowledge.com/esti/wokmws/ws/WOKMWSAuthenticate
I, [2017-09-27T08:58:32.938383 #12354]  INFO -- : Authorization: Basic {{SECRET_SNIPPED}}, SOAPAction: , Content-Type: text/xml;charset=UTF-8, Content-Length: 397
I, [2017-09-27T08:58:33.238701 #12354]  INFO -- : SOAP response (status 200)
[3] pry(main)> wos.session_id
=> "1F28d8jTIRdrY9Oi4aF"
[4] pry(main)> wos.auth.class
=> Savon::Client
[5] pry(main)> wos.search.class
=> Savon::Client
[6] pry(main)> wos.search.operations
=> …
```
=> Savon WSDL client for WOS SOAP API

spec/spec_helper.rb
The `Coveralls.wear!` disables the simplecov report on a dev laptop.  This PR enables the `Coveralls.wear!` on CI builds only, which allows SimpleCov to generate reports on a dev laptop, which can opened in a browser from
- `sul_pub/coverage/index.html`
=> Coveralls.wear only on CI builds

Gemfile, Gemfile.lock, spec/spec_helper.rb
This PR also makes the SingleCov utility available for more immediate feedback on coverage when running specs.  It is not enabled on every file now, but can be enabled just by adding the `SingleCov.covered!` to any spec file that your working on.
=> Enable simplecov

.travis.yml, Rakefile
Reduce cruft, improve accuracy.
The purpose was to avoid running CI in production, but that can be accomplished without a fork.
Do `db:setup` in Travis' `before_script`.  Now the `Rails.env.production?` check is unnecessary, because `RSpec` won't even be part of the bundle on a production system, so all it would do is run rubocop then fail harmlessly on a NameError.
This incorporates the changes from @mjgiarlo's gist:
https://gist.github.com/mjgiarlo/ee079cd476b94066886f6f541e624a5b
And resolves the double-running of spec and rubocop.
NOTE: Explicitly (re)defining the `:spec` task was part of the mechanism of duplication.
=> CI was running twice because of system fork out of Rakefile

Capfile, Gemfile, Gemfile.lock
This enables easy shell sessions for deployment targets, e.g.
```
$ bundle exec cap prod shell
Pseudo-terminal will not be allocated because stdin is not a terminal.
Executing ssh -t -A pub@sul-pub-prod.stanford.edu cd /opt/app/pub/sul-pub/current && $SHELL --login
[pub@sul-pub-prod current]$ 
```
This PR also addresses the deprecation warning about explicit requirements to use the git SCM plugin.
=> capistrano-shell

app/models/pubmed_source_record.rb, app/models/sciencewire_source_record.rb, lib/bibtex_ingester.rb, lib/science_wire_harvester.rb
A very simple subset of #235.  Remove `require` statements that are not useful for anything.
=> Require cleanup

spec/spec_helper.rb
Disable the requires for SingleCov by default.  It can interfere with RubyMine IDE test coverage because the IDE loads it's own copy of SimpleCov before running specs, which triggers an exception in SingleCov because it detects that SimpleCov is already loaded.
=> SingleCov enabled by running with env SINGLECOV=true

lib/science_wire_harvester.rb, spec/lib/science_wire_harvester_spec.rb
Distinguishing between the public API of a class and the internals is important to logic and refactorability.
All these methods are not invoked anywhere outside the class at runtime.
In one case, a method was invoked only in a test.  Since the test should not dictate the design of the class, I revised the spec to call `send` where the method is now `private`.
This shows us more than half the class was actually internal methods.
Split off from #235.
=> Move ScienceWireHarvester internal methods to private

lib/wos_records.rb, spec/lib/wos_records_spec.rb
Simply adds an `WosRecords#empty?` method.
=> WosRecords#empty?

config/settings.yml, lib/notification_manager.rb, lib/wos_client.rb, spec/fixtures/wos_client/wos_session_close_fault_response.xml, spec/lib/notification_manager_spec.rb, spec/lib/wos_client_spec.rb
While testing something is a stale console session, I ran into a rejected request because the SID had expired, so when I tried to reset it I couldn’t because the WosClient wasn’t handling the SOAP fault.  This PR will fix that.
This handles SOAP faults in the WosClient#session_close to ensure that it resets the session_id and other client objects.  It doesn't matter whether the session_close is successful or not, really, the session will expire after 4 hours of inactivity anyway.
- Adds exception handling for SOAP fault when closing a session that is not found
- Adds `NotificationManager.wos_logger`
- configuration added to `Settings.WOS.LOG`
- used in `WosClient#logger` private method
=> WosClient#session_close fault handing

lib/science_wire/harvest_broker.rb, spec/lib/science_wire/harvest_broker_spec.rb
Same principles as before.  Move internal methods to private and sort by alphanumeric order.
I also collapsed one test case that tested if the return value was an Array and Empty separately, to just test `.eq []` in one go.  No need to execute twice.
=> HarvestBroker also has methods that should be private

lib/tasks/sw.rake
Otherwise, in some environments it will fail w/:
`TypeError: no implicit conversion of Array into String`
=> Be explicit about formatting Array for output

lib/wos_records.rb, spec/lib/wos_records_spec.rb
WIP related to #264 
```ruby
wos_client = WosClient.new(Settings.WOS.AUTH_CODE, :info);
wos_queries = WosQueries.new(wos_client);
records = wos_queries.search_by_name('Altman, Russ');
records.count
#=> 464
records.by_database['WOS'].count
#=> 411
> records.by_database['MEDLINE'].count
#=> 53
```
=> WosRecords - select records by database prefix

config/schedule.rb
We don't need this rake task to run on an automated schedule anymore since nagios is configured to do these checks and email the appropriate person.  Leaving the underlying rake task in for now in case it is useful in the future.
=> remove scheduling of external services check

app/views/pages/clarivate_links.xml.erb, lib/clarivate/links_client.rb, spec/fixtures/clarivate/links_response.xml, spec/lib/clarivate/links_client_spec.rb
Example usage:
```ruby
client = Clarivate::LinksClient.new
=> #<Clarivate::LinksClient:0x007fdc8c54e640 @host="https://ws.isiknowledge.com", @password="xxxxx", @username="StanfordU_SW">
resp = client.links(['000346594100007', '000081515000015'])
Rendered pages/clarivate_links.xml.erb (0.1ms)
=> {
"000081515000015"=>{:pmid=>"10435530", :ut=>"000081515000015", :doi=>"10.1118/1.598623"}, 
"000346594100007"=>{:ut=>"000346594100007", :doi=>"10.1002/2013GB004790"}
}
```
TODO: 
- tests
- uncap limit of incoming ids, batch 50 per request
Fixes #193 
Fixes #252 
Fixes #247
=> Links AMR client and associated request template

app/models/author_identity.rb, lib/agent/author_address.rb, lib/agent/author_institution.rb, lib/agent/author_name.rb, lib/science_wire/author_attributes.rb, lib/science_wire/harvest_broker.rb, lib/science_wire_harvester.rb, lib/tasks/sw.rake, spec/integration/smart_query_spec.rb, spec/lib/agent/author_address_spec.rb, spec/lib/agent/author_institution_spec.rb, spec/lib/agent/author_name_spec.rb, spec/lib/science_wire/author_attributes_spec.rb, spec/lib/science_wire/harvest_broker_spec.rb, spec/lib/science_wire/query/conference_proceeding_document_suggestion_spec.rb, spec/lib/science_wire/query/journal_document_suggestion_spec.rb, spec/lib/science_wire/query/publication_query_by_author_name_spec.rb, spec/lib/science_wire/query/suggestion_spec.rb, spec/lib/science_wire_client_spec.rb, spec/lib/science_wire_harvester_spec.rb, spec/models/author_identity_spec.rb, spec/spec_helper.rb
Extract author name/address/institution stuff out of the SW module, it doesn't belong there.  Preparation for further work on #272 and also for later removing the SW module entirely.  This PR will be solely a refactor, to make sure this is done right first.
- the module cannot be named `Author`, as in `Author::Name` because there is already an `Author` model in the rails app and ruby/rails is not smart enough to differentiate between the rails model/class and a separate module.
- to check that all the things are changed, I used:
```sh
$ git grep 'ScienceWire::Author'
$ git grep 'ScienceWire::Author' | grep -v 'AuthorAttributes'
```
- unless some `git rebase` stuff is required, I think this is done and I need it (want it) to continue work on #272
=> Agent module

lib/tasks/sw.rake, lib/wos_queries.rb, spec/lib/wos_queries_spec.rb
Fix #271 
- this allows the consumer of the WosQueries object to provide any array of institutions
- the responsibility for setting the correct institutions lies with the consumer (Harvester, rake task etc.)
- this allows an author query without any institutions (previously impossible)
=> WosQueries - refactor to provide institutions parameter

app/models/publication_identifier.rb
Otherwise it is not identifying anything!
`inverse_of` is a recommended practice for associations.  Rails tries to auto-detect heuristically, but it is more reliable and efficient to declare the inverse.  See `Bi-directional associations` here:
https://apidock.com/rails/ActiveRecord/Associations/ClassMethods
Verified there are no records currently (on prod or cap-qa) that would run afoul of this constraint:
```ruby
PublicationIdentifier.where(publication_id:nil).count
=> 0
```
But let's keep it that way.
=> Every publication_identifier should be attached to a publication

lib/web_of_science/queries.rb, spec/lib/web_of_science/queries_spec.rb
- several private method bodies can be included in public methods
- extracted from #333 (and independent of it)
=> WebOfScience::Queries - remove some extraneous private methods

app/models/publication.rb
When you know you are going back to the DB to fetch the associated object for each record, just include that table in the first query and avoid **N+1** requests.
=> Avoid n+1 SQL queries

lib/clarivate/links_client.rb, spec/fixtures/clarivate/links_empty_results.xml, spec/lib/clarivate/links_client_spec.rb
Discovered a bug while working on the WOS harvester.  Extracted this from #333
=> Clarivate::LinksClient - fix bug when vals is empty

spec/models/publication_spec.rb
avoid declaring methods inside specs, use `let`.
=> Minor cleanup in spec

spec/api/sul_bib/authorship_api_spec.rb, spec/models/publication_spec.rb
See:
https://stackoverflow.com/questions/25188266/what-does-activerecord-do-with-arguments-passed-in-to-association-attribute-meth
This would help us in a potential Rails 5 upgrade.
=> Rails deprecation: Use .reload instead of association(true)

app/models/publication.rb
This is a weird copy/paste error that missed the context being different.  URIs are filesystem independent!  The tests already use regular string interpolation for the same value.
=> File.join is for *filesystem-dependent* composition, not URIs!

app/models/publication.rb, lib/tasks/cap_cutover.rake, spec/api/sul_bib/sourcelookup_spec.rb, spec/lib/doi_search_spec.rb, spec/models/publication_spec.rb
NOTE: for the purposes of this revision, I am treating `cap_cutover.rake` as a vestigial/deprecated piece of code. Where it is the sole (external) caller for one method, I am not treating that as
a continuing "current" use.  I edited it so the task will still work the same (by using `.send`, similar to the specs), but I am allowing `Publication` to take the otherwise private method private.
In a separate PR, most of `cap_cutover.rake` is being removed.
=> Publication model has methods that should be private

Gemfile, Gemfile.lock, lib/parse_identifier.rb, lib/parse_identifier_doi.rb, lib/parse_identifier_isbn.rb, lib/parse_identifier_pmid.rb, script/publication_identifier_normalization.rb, spec/factories/publication_identifier.rb, spec/lib/parse_identifier_doi_spec.rb, spec/lib/parse_identifier_isbn_spec.rb, spec/lib/parse_identifier_pmid_spec.rb, spec/lib/parse_identifier_spec.rb, spec/support/parse_identifier_shared_examples.rb
Fix #241 
Connected to #285 
Could be revised if https://github.com/altmetric/identifiers/pull/20 works out.
This PR adds a script to use the Altmetrics identifiers gem to extract DOI, ISBN & PMID from the PublicationIdentifiers.  The runner script can be used in a read-only mode to log the results or it can be used in a read-write mode to remediate the db-data.  In the read-write mode, it should update the PublicationIdentifier and the Publication.pub_hash['identifiers'].
On my laptop, I have a prod-db dump from early Oct, 2017.  I can run the following to test the identifier normalization and then review the log file output:
```
RAILS_ENV=production bundle exec rails runner script/publication_identifier_normalization.rb
```
It logs to `log/parse_identifier*`; the log files from a …
=> Normalize DOI, ISBN & PMID in PublicationIdentifiers & Publication.pub_hash

lib/web_of_science/identifiers.rb, lib/web_of_science/record.rb, spec/fixtures/wos_client/medline_record_24452614.xml, spec/fixtures/wos_client/wos_record_000288663100014.xml, spec/lib/web_of_science/identifiers_spec.rb, spec/lib/web_of_science/record_spec.rb
Required for #333 
Connected to #254 to code the business logic for the WOS harvester
Connected to #301 to code logic for de-duping new WOS-records to create new Pubs
This replaces #365 (although #365 was OK, it left the identifiers open to exploitation/corruption, alternative truths and all that is evil, Darth).
This class is entirely responsible for WOS identifiers and managing any inconsistencies there might be between how WOS names their identifiers and how sul_pub names them.  It's purpose is to be the sole gatekeeper between WOS and sul_pub.  In that role, it is tasked with protecting the identifiers as immutable data, but allowing very specific merges from the links-API data.  It's also responsible for parsing identifiers based on the type of WOS-DB providing the record and …
=> WebOfScience::Identifiers

script/publication_identifier_normalization.rb
The first thing `add_all_identifiers_in_db_to_pub_hash` does is:
```
publication_identifiers.reload if persisted?
```
Since this script only runs on persisted objects, that means it will do the same reload every time anyway.
=> Avoid reloading twice

lib/clarivate/links_client.rb, lib/tasks/wos.rake, lib/web_of_science/record.rb, lib/wos.rb, spec/lib/wos_spec.rb
Connected to #253 
The beginning of `wos:{x}` rake tasks.
- This adds WOS API utils module/singleton, available in rails console
- Added `wos:publication` task, based on `sw:publication` task
- Added `wos:links` task to get all the link fields for a publication
=> WebOfScience rake tasks - the saga begins

config/settings.yml
Required in #379 to populate the PubHash with a new source record provenance. 
- f291f9341a1da71fea30dcfbd8f7de946b316291
I assume we want to replace
```ruby
pub_hash[:provenance] = Settings.sciencewire_source
```
with say
```ruby
pub_hash[:provenance] = Settings.wos_source
```
What provenance do we want to use for Web of Science records?  This PR is a suggestion, I'm open to alternatives.  We seem to be using `wos` in our common vocab on this work.
=> WOS provenance setting

lib/notification_manager.rb, lib/web_of_science/harvester.rb, lib/web_of_science/process_records.rb, spec/lib/web_of_science/harvester_spec.rb, spec/lib/web_of_science/process_records_spec.rb
Fix #272 to use an `Agent::AuthorName` and `Agent::AuthorInstitution` for WOS searches
Fix #254 to code the business logic for the WOS harvester
Fix #326 to log possible exceptions in the LinksClient calls
Fix #301 to code logic for de-duping new WOS-records to create new Pubs
Fix #392 integrate with LinksAmr
Connected to #317 - design discussions on the WOS harvester
This PR focuses on
- using the AuthorName and AuthorInstitution to issue an author query
- saving WebOfScienceSourceRecords
- integrating links-API data into `WebOfScience::Record#identifiers`
This PR _does not_ attempt to:
- create new `Publication` records
- create new `PublicationIdentifier` records
- these two goals depend on mapping the PubHash data
TODO:
- create pending tests and ticket work to get that stuff done
- …
=> WebOfScience::Harvester

config/deploy/cap-qa.rb, config/deploy/prod.rb, config/schedule.rb
currently prod and cap-qa run their fortnightly harvests on the exact same day, just staggering the hour and minute start time -- this fixes the start hour and time but staggers them 5 days apart so they will not run concurrently
=> Adjust scheduling of harvesting rake tasks on qa and prod so that will not run concurrently

app/models/publication.rb, app/models/pubmed_source_record.rb, spec/models/publication_spec.rb
Fix #425 
A primary public method on this class should return an instance of the class, not a result of calling one of the instance methods.  The consumer can call the instance method(s).
=> Pubmed public api

lib/harvester.rb, lib/harvester/base.rb, spec/lib/harvester/base_spec.rb, spec/lib/science_wire_harvester_spec.rb
Connected to #254
This is mostly a demonstration.  The main takeaway is starting from an Enumerable of Authors and not having to deal with a bunch of externalizable logic about author selection or batching. Note that `harvest` still operates on an Enumerable of `Author`s, so one given subclass might do:
```ruby
def harvest(authors)
authors.each { |author| harvest_one(author) }
end
```
while another that hypothetically supports querying, say, 10 authors at once might (re-)batch.  
```ruby
def harvest(authors)
authors.each_slice(10) { |slice| harvest_ten(slice) }
end
```
Neither has to worry about *any* author selection logic unless it wants to.  Any prevailing pattern that would need to be implemented can be done externally (e.g. single author is trivial), or in the base class thereby …
=> A simple Harvester base class

spec/lib/doi_search_spec.rb
Merge! the provenance.
Not a very good spec if this didn't make any difference.
=> PublicationsController#sourcelookup by doi - spec merge! provenance

lib/notification_manager.rb, lib/web_of_science/record.rb
Extracted from #379 
This will enable logging exceptions when processing WOS record data.
=> WebOfScience::Record - use the wos_logger

lib/web_of_science/mapper.rb, spec/lib/web_of_science/mapper_spec.rb
Extracted from #379 for easier review here
This is the base class for all the pub_hash mappers in #379
=> WebOfScience::Mapper - base class for record data mappers

app/api/sul_bib/authorship_api.rb, app/api/sul_bib/publications_api.rb, app/models/contribution.rb, app/models/publication.rb, lib/doi_search.rb, lib/pubmed_harvester.rb, lib/tasks/sul.rake, script/fix_sw_procs_marked_as_article.rb, script/missing_wos_ids.rb, script/rebuild_conference_papers.rb, spec/api/sul_bib/publications_api_spec.rb, spec/models/contribution_spec.rb, spec/models/publication_spec.rb
Existing validations were ad hoc and required the caller to interrogate potential values before instantiating the model. Afterwards model state was not validatable.
ActiveRecord validations offer a more comprehensive and reliable approach. This PR guarantees `publication` and `author` associations (already true for prod data). It also validates values for `visibility` and `status` in the conventional way, demonstrated in tests. See:
http://guides.rubyonrails.org/active_record_validations.html
Note: this does NOT make `visibility` and `status` values required, because production data has already allowed `nil` values, even for `featured` (a boolean field):
```ruby
pry(main)> Contribution.group(:status).count
=> {nil=>4, "approved"=>318802, "denied"=>134889, "new"=>302397,
"unknown"=>138209} …
```
=> Stronger validation for Contribution model

lib/web_of_science/records.rb
Extracted from #379 
This enables random sampling of records from WOS-records (the `:to_a` comes from `Enumerable` and `sample` is from `Array`; there's no need to test these ruby functions, it works nicely in the console).
=> WebOfScience::Records - #sample returns random record

app/models/contribution.rb, spec/models/contribution_spec.rb
The problem is calling attribute getter methods on objects that are initialized via `.select(:id)` since they only have a partial set of fields (i.e. one) in their `attributes` hash, meaning calling the
attribute getter method raises an error.
=> Fix OK Computer checks on Contribution

Gemfile, Gemfile.lock, lib/web_of_science/map_abstract.rb, lib/web_of_science/map_citation.rb, lib/web_of_science/map_names.rb, lib/web_of_science/map_pub_hash.rb, lib/web_of_science/map_publisher.rb, lib/web_of_science/record.rb, spec/fixtures/wos_client/wos_record_000268565100019.xml, spec/lib/web_of_science/map_abstract_spec.rb, spec/lib/web_of_science/map_citation_spec.rb, spec/lib/web_of_science/map_names_spec.rb, spec/lib/web_of_science/map_pub_hash_spec.rb, spec/lib/web_of_science/map_publisher_spec.rb, spec/lib/web_of_science/record_spec.rb
Fix #383 
Fix #368 
Isolating components of #375 
- this isolates only the `toPubHash` method from d86ae6f653ae189e11ed294c3b63468afc1ac926
TODO:
@Maatary 
An informal integration test was used to develop and revise this by checking how it handles some WOS records, e.g. using the `bundle exec rails c` console, the records should all parse without exceptions:
```ruby
altman_records = WOS.queries.search_by_name('Altman, Russ, B', ['Stanford University']);
altman_records.map(&:pub_hash)
altman_records.map {|rec| ph = PubHash.new(rec.pub_hash); ph.to_apa_citation }
```
=> WebOfScience::Record#pub_hash

app/api/sul_bib/authorship_api.rb, app/api/sul_bib/publications_api.rb, app/controllers/authors_controller.rb, app/models/author.rb, app/models/publication_identifier.rb, app/models/pubmed_source_record.rb, app/models/sciencewire_source_record.rb, app/models/web_of_science_source_record.rb, lib/agent/author_name.rb, lib/cap_authors_poller.rb, lib/cap_http_client.rb, lib/csl/citation.rb, lib/harvester/base.rb, lib/identifier_normalizer.rb, lib/identifier_parser.rb, lib/notification_manager.rb, lib/science_wire/api/publication_items.rb, lib/science_wire/id_suggestions.rb, lib/science_wire_client.rb, lib/science_wire_publication.rb, lib/science_wire_publications.rb, lib/web_of_science/harvester.rb, lib/web_of_science/identifiers.rb, lib/web_of_science/map_publisher.rb, lib/web_of_science/process_records.rb, lib/web_of_science/queries.rb, lib/web_of_science/record.rb, lib/web_of_science/records.rb, lib/web_of_science/xml_parser.rb
- `@return` doesn't get a name like `@param` does
- use `@!attribute [r]` for `attr_reader`, not just `@return`
- Commas, not pipes to delimit variations
- Added a few new YARD lines, expanded on others (e.g. `Hash<X => Y>` instead of just `Hash`)
- Default values are already interpreted by YARD from method declaration
=> YARD corrections

lib/web_of_science/record.rb, spec/fixtures/wos_client/wos_record_000386326200035.xml, spec/lib/web_of_science/record_spec.rb
Split out of #379 
I reviewed Russ Altman records to find examples of different roles, using:
```ruby
roles = altman_records.map {|rec| [rec.uid, rec.to_xml.scan(/(role=".*?")/) ] };
```
There are `author`, `book_editor` and `publisher` roles that apply to agents.  There is also a `researcher_id` role but that seems specific to WOS metadata management or something.
=> WOS record editors

config/settings.yml, lib/web_of_science/process_records.rb, spec/lib/web_of_science/process_records_spec.rb
Fix #419 
Selects only WOS & MEDLINE records for processing, using a configuration setting to specify what databases are allowed to be processed.
=> WOS filter databases

app/models/publication.rb, spec/models/publication_spec.rb
The values would have been coecred by Contribution, IF we passed them to the initializer.  Instead we use `first_or_initialize` and then `assign_attributes`, so we need to correct them in Publication first.
Fortunately, that is simple to accomplish.
=> Resolve passing of invalid values to Contribution model from Publication

spec/tasks/cleanup_rake_spec.rb
Note this is PR on @peetucket's branch, not `master`.
- use `let` statements that fully establish "allowances" for the objects, so that their behavior in the example is not continually undergoing incremental additional revision
- test behavior, not implementation.  that is to say, instead of relying on the test knowing that methods X, Y and Z should be called in order, just check the result.  Free up the implementation to refactoring later.
More could be done here, but I'm not sure time constraints warrant it.
=> Revisions to propsed rake spec

app/models/web_of_science_source_record.rb, spec/models/web_of_science_source_record_spec.rb
Connected to #506 or anything that needs to instantiate a `WebOfScience::Record` from the active record db data.
=> WebOfScienceSourceRecord#record returns a WebOfScience::Record

lib/notification_manager.rb
Split out of #454 
The app has a lot of `rescue` code that should only handle `StandardError`, this is the only one in the `NotificationManager`.
=> NotificationManager#error - rescue StandardError

config/initializers/config.rb
Conceivably this helps encapsulate overrides for Travis.
Example test you can perform locally, say in `spec/config_spec.rb`:
```ruby
describe 'config gem, how do u work?' do
it 'overrides from ENV' do
expect(Settings.WOS.enabled).to eq(true)
end
it 'reads from ENV' do
expect(Settings.whatever).to be_nil
end
it 'handles underscores' do
expect(Settings.SULPUB_ID.PUB_URI).to eq('http://sulcap.stanford.edu/publications')
end
end
```
Then run these to see the difference in behavior:
```bash
rspec spec/config_spec.rb # passes
SETTINGS__WOS__enabled=false rspec spec/config_spec.rb # 1st fails
SETTINGS__whatever=foobar rspec spec/config_spec.rb    # 2nd fails
SETTINGS__SULPUB_ID__PUB_URI=www.google.com rspec spec/config_spec.rb # 3rd fails
```
The gem behavior is defined …
=> Allow Config gem to pull from ENV values/overrides

config/settings.yml, spec/spec_helper.rb
Connected to #490 
Outcome of review on #454 to allow some CAP API settings to be public.
- updated the travis.ci ENV values.
- this needs to work with the old cap-client, which does not accept the `https://` prefix.
=> CAP API settings are public

lib/web_of_science/queries.rb
fix #542 
Works on my laptop prod-console, e.g.
```ruby
PRODUCTION [1] pry(main)> altman = Author.find_by(cap_profile_id: 4706);
PRODUCTION [2] pry(main)> WebOfScience.harvester.process_author(altman)
I, [2017-12-12T11:55:08.493366 #11638]  INFO -- : SOAP request: http://search.webofknowledge.com/esti/wokmws/ws/WOKMWSAuthenticate
I, [2017-12-12T11:55:08.493649 #11638]  INFO -- : Authorization: Basic [SECRET], SOAPAction: , Content-Type: text/xml;charset=UTF-8, Content-Length: 352
I, [2017-12-12T11:55:08.717947 #11638]  INFO -- : SOAP response (status 200)
I, [2017-12-12T11:55:08.823310 #11638]  INFO -- : SOAP request: http://search.webofknowledge.com/esti/wokmws/ws/WokSearch
I, [2017-12-12T11:55:08.830509 #11638]  INFO -- : Cookie: SID="5DcrjsxMhIizMPNZTYC", SOAPAction: , Content-Type: …
```
=> WebOfScience::Queries#search - fix message composition for userQuery

app/models/publication.rb, spec/models/publication_spec.rb
`git grep update_from_sciencewire` hits only the lines removed.
=> Remove unused method, soon to become even more unused

spec/spec_helper.rb
Code climate relies on SimpleCov for code coverage reports.  Adjusting this setting could avoid some breaking builds when there are minor changes in coverage (often due to refactoring legacy code).
=> SimpleCov - maximum coverage drop set to 1%

app/models/publication.rb
Old behavior generated two queries unnecessarily, and with scalability issues:
```sql
SELECT DISTINCT `publications`.`id` FROM `publications`
INNER JOIN `contributions` ON `contributions`.`publication_id` = `publications`.`id`
INNER JOIN `authors` ON `authors`.`id` = `contributions`.`author_id` 
WHERE `authors`.`active_in_cap` = 1
SELECT `publications`.* FROM `publications`
WHERE `publications`.`id` IN (434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, …
```
=> Convert with_active_author to a scope, 1 SQL query, not 2

app/models/author.rb, db/migrate/20171208233331_author_cap_profile_id_uniqueness.rb, db/schema.rb, spec/lib/cap_authors_poller_spec.rb, spec/models/author_spec.rb
Belt and suspenders approach here:
- model validation
- database constraint
I verified that there are no duplicate `cap_profile_id` values on
production server, so no data repair/salvage will be necessary:
```ruby
Author.select(:id, :cap_profile_id).group(:cap_profile_id).having("count(*) > 1")
=> []
```
This will help simplify API logic that runs in circles worrying that maybe `cap_profile_id` is not unique enough.
=> Add unique constraint to Author cap_profile_id

db/migrate/20171213201429_wos_src_record_medium_text.rb, db/schema.rb
Fix #547
Note that the source data is also assigned to `Publication#xml`, which is already a `:mediumtext` field
- https://github.com/sul-dlss/sul_pub/blob/master/db/schema.rb#L138
- to fix #547, only the WOS source record needs to be extended
The WOS harvest failed to save some long records.  This PR expands the source record capacity to handle large WOS records.  A review of the harvest logs identified some large records that failed to save; the largest of those records should now fit in this expanded field.  (The logs had some db ROLLBACK errors that were all related to this.)
=> WebOfScienceSourceRecord#source_data converted to mediumtext length

lib/cap_profile_id_rewriter.rb
DISABLES cap_profile_id_rewriter class, per agreement.
- Only one method here is ever invoked. Make everything else private.
- Remove unnecessary `dotiw` dependency. The `DateHelper` is good enough.
- Completely avoid all the kludgey instance variables and initialization.
- Cut out all the logging of variables that NEVER CHANGE. They are uninformative.
- Cut out the DUPLICATE log lines.
- Add YARD
- Ensure logs get written, even after a `rescue`
- Consolidate `Author` finding logic
- Add `!` to critical operations
We have a blocker in production data to the **existing** logic of this class, specifically documented in #546.
Ironically, this class that complicates making `cap_profile_id` unique, also requires `cap_profile_id` to be present AND requires 3 other fields to be unique.
=> Rework cap_profile_id_rewriter, disable it for now

app/api/sul_bib/authorship_api.rb, app/models/contribution.rb, spec/models/contribution_spec.rb
This extends #523.  Now rebased after that PR was merged.
=> Convert bespoke "validations" to ActiveRecord basis

app/models/author.rb, spec/api/sul_bib/authorship_api_spec.rb, spec/models/author_spec.rb
All author records on prod indeed have `cap_profile_id`.
I don't know if we are going to care about this in this work cycle, but I already had this commit on a different branch, so I cherry-picked it here.
With the rewriter locked down, I think we could merge this without difficulty.
=> Validate cap_profile_id presence, too

db/migrate/20171215001732_wos_source_record_integer_pmid.rb, db/schema.rb
All the PMID fields are Integers - overlooked when first creating it.
cf. https://github.com/sul-dlss/sul_pub/blob/master/db/schema.rb
```
$ grep 'pmid' db/schema.rb 
t.integer  "pmid",                    limit: 4
add_index "publications", ["pmid"], name: "index_publications_on_pmid", using: :btree
t.integer  "pmid",               limit: 4
add_index "pubmed_source_records", ["pmid"], name: "index_pubmed_source_records_on_pmid", using: :btree
t.integer  "pmid",               limit: 4
add_index "sciencewire_source_records", ["pmid"], name: "index_sciencewire_source_records_on_pmid", using: :btree
t.integer  "pmid",               limit: 4
t.integer  "pmid",               limit: 4
add_index "web_of_science_source_records", ["pmid"], name: "web_of_science_pmid_index", using: :btree
```
=> WebOfScienceSourceRecord#pmid converted to Integer

fixtures/vcr_cassettes/WebOfScience_ProcessRecords/with_WOS_records/behaves_like_pubs_with_pmid_have_mesh_headings/persists_PMID_and_publication_pub_hash_has_MESH_headings.yml, lib/web_of_science/process_records.rb, spec/lib/web_of_science/process_records_spec.rb
Fix #549 
- first create publication and contribution records
- then enhance select records with PubMed data
- isolate the Publication creation from PubMed failures
- provide better exception log messages using NotificationManager
- isolate WOS links update failures to individual records
- add record-specific log messages (could help identify problematic records)
- fixed a typo in a spec for "creates new contribution in the pub_hash[:authorship]"
=> WebOfScience::ProcessRecords - separate pub creation from pubmed additions

app/models/web_of_science_source_record.rb, spec/models/web_of_science_source_record_spec.rb
Fix #562 
- use `WebOfScience::Record` for defaults and other util methods
=> WebOfScienceSourceRecord - safe init callback and cleanup field accessors

app/models/web_of_science_source_record.rb, spec/models/web_of_science_source_record_spec.rb
Extracted from #551 to focus on this change alone.
Update: rebased on #559 (converted PMID to Integer) and fixed spec
=> WebOfScienceSourceRecord - set identifiers, if not already set

spec/api/sul_bib/publications_api_spec.rb, spec/factories/author.rb
- common `let` statements (that are about their return values, not about establishing a context)
- removed unused `let` statement
- converted another to a `before` block, since the return values weren't being used, it was really about establishing context
- AVOID SERIALIZING/DESERIALING JSON... SERIALLY
- Manipulate hashes, serialize to JSON later
- Corrected some description statements that were lying about the numbers inolved
- Removed a single-use factory that was materially no different than the base factory, but had a name that suggested it did something special.
- harness the power of RSpec `include`
These changes are not as comprehensive as the previous ones on authorship_api_spec, but
they are a great improvement in performance and readability.
=> Similar refactoring comes to publications_api_spec

lib/web_of_science/client.rb, spec/lib/web_of_science/client_spec.rb, spec/lib/web_of_science_spec.rb
Without this, they log to STDOUT.
=> WebOfScience::Client - savon clients log to WebOfScience.logger

app/api/sul_bib/authorship_api.rb, spec/api/sul_bib/authorship_api_spec.rb, spec/fixtures/wos_client/wos_record_000386326200035.xml
The only open question I might have is about relative priority the various backends when multiple pub ID types are received.  I atomized `get_publication` into parts because it was getting unwieldy, and the logic for WoS required an additional argument (`author`).  The priority order should also be more obvious, anticipating we might want to tweak it.
fixes #408
=> Xtend authorship api for wos

Gemfile
Trying to fix this when the app is deployed without the `:test` bundle, but rake requires rspec tasks.
```
[pub@sul-pub-dev current]$ bundle exec rake cap:poll[1]
Unable to load RSpec.
```
=> Gemfile - rspec without require

config/settings.yml, lib/web_of_science/process_records.rb
- the XML doesn't need to be saved in Publication, it's already in WebOfScienceSourceRecord
- the savon clients 'info' log level is high volume and low information content
- it will just fill logs with mostly useless details
- the only value is the session-ID and response status, but we don't care for 200 responses anyway
=> WOS harvest efficiency

spec/spec_helper.rb
Split out of #583 
This is just catching up on tech-debt for using VCR on linksAMR calls that are not entirely mocked.
=> SpecHelper - VCR filters for the Links AMR service

lib/web_of_science/harvester.rb, lib/web_of_science/queries.rb, spec/lib/web_of_science/queries_spec.rb
Extracting this from #583 to focus only on the query changes in this PR.
- push the query message details into the public API
- allow clients to inspect and modify the query message details
- this becomes important in the harvester - to retrieve only WOS-UIDs for queries, not full records
- provide new options to query for record fields (or no fields at all)
- prior to this change, it was only possible to retrieve full records
- retrieving full records is too expensive when they have already been harvested
- the `viewField` is described in the WOS API doc on p. 37 and it can be used to retrieve only the UID
- changes the `search` method signature, which might break existing clients
- need to check specs and all calls to any methods that change
- adds utility method to return empty records …
=> WebOfScience::Queries - surface query messages in the public API

spec/factories/pubmed_source_records.rb, spec/fixtures/pubmed/pubmed_record_10000166.xml
Extracted from #512 
There are no real PubMed fixture data, this adds one real example.
=> PubmedSourceRecord - add a real fixture example for PMID 10000166

lib/web_of_science/identifiers.rb, lib/web_of_science/map_abstract.rb, lib/web_of_science/map_citation.rb, lib/web_of_science/map_mesh.rb, lib/web_of_science/map_names.rb, lib/web_of_science/map_pub_hash.rb, lib/web_of_science/map_publisher.rb, lib/web_of_science/mapper.rb, lib/web_of_science/record.rb, spec/lib/web_of_science/map_mesh_spec.rb, spec/lib/web_of_science/record_spec.rb
Fix #601 
Atomic refactoring to remove memoized data wherever possible (resting on green)
- simplify the public API for the WOS Record class
- removed the `summary*` methods, access to this data is in the `to_h` & `to_struct` methods
- spec changes should be related to public API changes only
- simplify mappers
- as a result of some extract class refactoring, there was some complexity in the mappers
- the mappers were holding onto the record
- mappers no longer hold onto a reference to the WOS record
- mappers extract only the WOS XML elements they need
- instances of mappers are no longer memoized anywhere
- the goal is to use less memory and make it easier for ruby GC to clean up
- most of the mapper refactoring rests on green in existing specs, so minimal changes to specs
=> WOS record and mappers use less memory

lib/web_of_science/client.rb, spec/lib/web_of_science/client_spec.rb
Split out of #583 
This is motivated by debugging the WOS harvest.  The WOS savon client logs contain a lot of repetitive noise.  Splitting out that logging to a separate file makes it easier to see actual WOS harvest log content without all the noise.
=> WebOfScience::Client - log to a different log file for routine client logs

spec/lib/csl/citation_spec.rb
=> Csl::Citation - remove obsolete sync_publication_hash spec in comments

spec/spec_helper.rb
Some new API code could retrieve WOS records and create new VCR recordings (when a savon mock is not used).  This PR will filter our authentication code from any VCR recordings that match the WOS-API authentication URI.
=> VCR - add filter for Settings.WOS.AUTH_CODE

lib/csl/mapper.rb, lib/csl/sciencewire_mapper.rb
Extracted from #512
This is a straight extract-class refactor to clarify responsibilities for the Csl::Mapper class.
=> Csl::Mapper - extract class Csl::SciencewireMapper

lib/csl/mapper.rb, lib/csl/pubmed_mapper.rb
Extracted from #512 
This is a straight extract-class refactor to clarify responsibilities for the Csl::Mapper class.
=> Csl::Mapper - extract class Csl::PubmedMapper

lib/csl/cap_mapper.rb, lib/csl/mapper.rb
Extracted from #512 
This is a straight extract-class refactor to clarify responsibilities for the Csl::Mapper class.
- this PR also applies extract-method refactor to the create_csl_report to fix cognitive complexity
=> Csl::Mapper - extract class Csl::CapMapper

lib/web_of_science/harvester.rb, spec/api/sul_bib/authorship_api_spec.rb
This is a follow-up to #596 
- the delegated methods can be private in the harvester
- this also modifies a query mock for the authorship-api to bring it into line with this change
- this mock might have been broken by #596 and surfaces in #583 as new VCR recordings
=> WOS queries singleton for harvester

lib/web_of_science/process_records.rb, spec/lib/web_of_science/process_records_spec.rb
Extracted from #583 to focus on this class in this PR.
- aims to reduce memory consumption by using a mutable array of records
- progressive filters now select or reject records in-place
- initialize no longer holds onto the original set of records
- they are immediately filtered for accepted-dbs
Fix #600
=> WebOfScience::ProcessRecords - convert records to a mutable array

lib/web_of_science/harvester.rb, lib/web_of_science/query_author.rb
Clarify responsibility for WOS-harvester
- consolidate author name-institution query in WebOfScience::QueryAuthor
- only needs to fetch and return WOS-UIDs for an author
- work in a later PR can address how to handle author alternate identities, that's not the scope of this PR
- this PR just defines the responsibility for any WOS author queries lies with this class
=> WebOfScience::Harvester - extract class WebOfScience::QueryAuthor

app/api/sul_bib/publications_api.rb
Use the more idiomatic construction.  Split from #631
=> Use `.find_by(...)`, not `.where(...).first`

app/models/publication.rb, spec/models/publication_spec.rb
Split from #631 
This removed 3rd parameter is not part of the tests and subsequent changes will remove it from method sig.  This clears the way for that change to be minimal.  
Avoid munging Hash param in `update_manual_pub_from_pub_hash`, with test.
=> Test targeting & param non-munging

app/controllers/publications_controller.rb, spec/controllers/publications_controller_spec.rb
Rails `render` has `body` param, not `text`
See: http://guides.rubyonrails.org/layouts_and_rendering.html#using-render
=> Fix rails output for 404

.rubocop_todo.yml, app/api/sul_bib/publications_api.rb, spec/api/sul_bib/publications_api_spec.rb
This adds tests for the other record types also, which were lacking.
Reworked a `case` statement that had no thing being cased!
@darrenleeweber effectively approved this commit (back when it had a different pre-rebase hash) in https://github.com/sul-dlss/sul_pub/pull/631/commits/f1ea3a52f4a456b0047527b15ce79083db9b26e5#r162755918
=> Avoid overwriting WOS records when targeted for "manual" update

spec/factories/pub_hash.rb
- factory needs to explicitly identify `class: Hash`
- since there is no persistence, `skip_create`
Fixes #664
=> Resolve FactoryBot.lint problem with pub_hash factory

lib/pubmed_client.rb
`.post` is a `Faraday::Connection` object public method, as documented here:
https://github.com/lostisland/faraday/blob/master/lib/faraday/connection.rb#L158
Using indirection to unnecessarily `.send` to a public method is anti-pattern.
Also added YARD to clarify the method can take String or `Array` of Strings, and the return value is a String.
=> Don't send to a public method: call it!

app/models/publication.rb
Real equivalence test, not just `include?`.
Prod data was confirmed to be all lowercase in #625.  
I leave open the question of whether a WoS record is `authoritative_pmid_source?` (only `pubmed_harvester.rb` cares).
=> Consolidate handling of `provenance` and make real comparisons

app/models/publication.rb
We can tell the argument is never invoked because of:
```bash
$ git grep -e update_manual_pub_from_pub_hash -e build_new_manual_publication app/ lib/ |grep -v "^app/models/publication.rb"
app/api/sul_bib/publications_api.rb:        pub = Publication.build_new_manual_publication(pub_hash, original_source)
app/api/sul_bib/publications_api.rb:      old_pub.update_manual_pub_from_pub_hash(new_pub, original_source)
```
Previous discussion here:
https://github.com/sul-dlss/sul_pub/pull/631/commits/562cf2d99fb60c97d79c27e6877beae4d9d6c5ed
(Though that will probably disappear after rebase.)
=> Remove unused 3rd argument from 2 manual-related methods in Publication

lib/harvester/base.rb
Extracted from #644 - trivial change to decrease memory load on harvests - the WOS harvest is so slow that queues of larger batch sizes are just extra load on memory.
- diff-coverage seems absurd on this PR
=> Harvester::Base - decrease the author batch size

lib/web_of_science/client.rb, spec/lib/web_of_science/client_spec.rb
Fix #522 
- the idea here is that every time there is _any_ query on the WOS-API, it must hit the `WebOfScience::Client#search` method, so it can count the queries.
=> WebOfScience::Client - manage session throttle limits

lib/cap/authors_poller.rb, script/delete_missing_auths.rb
Publication's `before_save` already does:
```
sync_publication_hash_and_db if pubhash_needs_update?
```
which in turn calls `rebuild_authorship` that does exactly the same two things desired by these callers:
```
add_all_db_contributions_to_my_pub_hash
set_last_updated_value_in_hash
```
=> Rely on before_save callbacks instead of explicit calls

lib/web_of_science/contributions.rb
Extracted from #644 
- minor changes to `WebOfScience::Contributions` methods
- let `Publication.where(wos_uid: uids).find_each` manage the work load
- refactor `contribution_by_identifier?` into two methods
=> WebOfScience::Contributions - tweaks

spec/factories/publication_identifier.rb, spec/lib/identifier_normalizer_spec.rb
Also remove a bunch of unused `let` statements.
Factories by default extrapolate URI from value.  Cases that need empty URI's are now obvious: they pass `identifier_uri: nil`.
=> More versatile factory, not a dozen bespoke single-use factories

lib/web_of_science/queries.rb
diff-coverage of 0% is useless to fail on, imo.
=> Avoid collision between variable name and `retrieve_options` method

lib/web_of_science/process_record.rb, spec/fixtures/pubmed/pubmed_record_21253920.xml, spec/lib/web_of_science/process_record_spec.rb
Connected to #639, #673 
This class could be used by anything that needs to process only one WOS-record, e.g. an API request for one record or a background jobs process for async processing.
This opens up some follow-on possibilities.  This class could be used inside the WOS-process-records class (but, if so, it might forgo some enumerator optimizations there; not sure).  This class could be attached directly to the WOS-record class as in `WebOfScience::Record#process` or something.
=> WebOfScience::ProcessRecord

lib/web_of_science/map_pub_hash.rb
This makes it clear which elements are guaranteed to be in the hash and which may or may not be included.
=> Reorganize hash assembly for clarity

app/controllers/publications_controller.rb, app/models/publication.rb, fixtures/vcr_cassettes/DoiSearch/_search/ScienceWire_enabled_WOS_disabled/behaves_like_sciencewire_one_hit/returns_Array_of_one_document_Hash_.yml, fixtures/vcr_cassettes/DoiSearch/_search/ScienceWire_enabled_WOS_disabled/queries_sciencewire_if_the_local_pub_match_is_not_DOI-reliable.yml, lib/doi_search.rb, spec/lib/doi_search_spec.rb
- honors configs
- for wos, ensures FULL doi string match returned if available
I don't care about "cognitive complexity" for this method at the moment.  The two things I anticipate doing to resolve that are:
1. Eventually ripping out the ScienceWire code, obviously
2. Moving the DOI full match stuff deeper into the stack, e.g. WOS `Queries`
Given the decent test coverage and temporary nature, I'm willing to punt on the CoCliCogCom, for now.
=> DoiSearch against WOS

lib/web_of_science/process_pubmed.rb, lib/web_of_science/process_records.rb, spec/lib/web_of_science/process_pubmed_spec.rb
Fix #640 & https://app.honeybadger.io/projects/50046/faults/36312445#notice-summary
- extract module to process pubmed enhancements
- the new public methods need additional specs
- WOS data contains hundreds of missing/bad PMID values, when it's bad:
- remove the PMID from the Publication and PublicationIdentifier data
- but when the PubMed API is not responsive, don't cleanup any PMIDs
=> WebOfScience::ProcessPubmed enhancements

app/models/publication.rb, app/models/pubmed_source_record.rb, fixtures/vcr_cassettes/PubmedHarvester/_fetch_remote_pubmed/WOS_and_ScienceWire_both_disabled/searches_only_pubmed.yml, fixtures/vcr_cassettes/PubmedHarvester/_fetch_remote_pubmed/WOS_disabled_ScienceWire_enabled/searches_only_ScienceWire.yml, fixtures/vcr_cassettes/PubmedHarvester/_fetch_remote_pubmed/WOS_enabled_ScienceWire_disabled/searches_only_WOS.yml, lib/pubmed_harvester.rb, spec/factories/publication.rb, spec/lib/pubmed_harvester_spec.rb
Fix #690 
- Broke out the remote searching to a private_class_method.
- Changed the expectations w/ regards to local hits based on analysis of actual duplicate values in #693. No reason to present the user with indifferentiable duplicate records.
- Honor configs
100% disinterested in Code Climate Cognitive Complexity for the same reasons as before, already anticipating removing SW code, which would make it pretty basic.  This PR reduces the flagged complexity from 13 to 8.
=> Pubmed from WOS

lib/harvester/base.rb
Open the harvest base class to harvesting options.  The base class is agnostic to any details of the options and uses none by default.
=> Harvester::Base - allow options

lib/web_of_science/harvester.rb, lib/web_of_science/query_author.rb
This is a necessary first step toward an alternative implementation to #699 
- this propagates generic options into the author harvest and queries
- it defaults to empty options
=> WOS harvester options

fixtures/vcr_cassettes/WebOfScience_QueryAuthor/_uids_with_symbolicTimeSpan/returns_a_small_Array_String_of_WOS-UIDs.yml, fixtures/vcr_cassettes/WebOfScience_QueryAuthor/_uids_without_symbolicTimeSpan/returns_a_large_Array_String_of_WOS-UIDs.yml, lib/web_of_science/query_author.rb, spec/lib/web_of_science/query_author_spec.rb
The error seems legitimately related to ruby hash order (default: order of key insertion), but the solution is to specify order for Savon/Gyoku's XML builder to use.
=> Explicit order where required

app/models/publication.rb, spec/api/sul_bib/publications_api_spec.rb, spec/models/publication_spec.rb
This should keep us from writing empty data back to the pub IDs table, especially during trying to clean up that same data.
Related to #285
=> Sync identifiers in pub hash checks

spec/fixtures/wos_client/authenticate_wsdl.xml, spec/fixtures/wos_client/search_wsdl.xml, spec/lib/web_of_science/client_spec.rb, spec/lib/web_of_science/wsdl.rb, spec/spec_helper.rb
Try to lighten the load of VCR recordings for WOS specs.  The intention of this PR is to provide two generic methods that stub the retrieval of WSDL data for the authentication and search endpoints of the WOS-API.  It's beyond the scope of this PR to apply them everywhere, which can be done in follow on PRs.
- if it were possible, it would be better to initialize the `WebOfScience::Client` with these files every time so that the auth and search Savon clients could be initialized with them.  AFAICT, this is not an option for the Savon client, it only accepts a WSDL URL.  If I'm wrong about this (and I hope so), then these fixture files could be used as such and the nature of this PR would change substantially - the focus could shift from using these fixtures in specs only to using them all …
=> WebOfScience WSDL stubs

lib/web_of_science/contributions.rb, lib/web_of_science/process_record.rb, lib/web_of_science/process_records.rb
Most of the work here is in `WebOfScience::Contributions`.
- use `find_or_create_by!` with a block to collapse two methods.  
- several guard clause checks move further up the chain
- Avoid querying `publication_identifiers` up to 4x serially by using an single query covering all 4 types.  The volume of these queries were indicated as one bottleneck in #671.
- Return fewer Booleans.  Instead: for the `true` case, return an object the caller might use (to avoid another query), for `false`, return `nil`.  
The resulting SQL (from execution) looks like:
```
SELECT  `publications`.* FROM `publications` INNER JOIN `publication_identifiers` ON `publication_identifiers`.`publication_id` = `publications`.`id` 
WHERE (publication_identifiers.identifier_value IS NOT NULL AND ( …
```
=> Query efficiently

Gemfile, Gemfile.lock, spec/spec_helper.rb
- `pubmed_search`: `PubmedSearch` unused;
- `responders`: provides `responders` and `respond_with`, both unused;
- `single_cov`: dev tool, not used;
- `turnout`: rack middleware for going into "maintenance mode", unused;
- `web-console`: not relevant for a JSON API.
- `bio`: a **bio-informatics** lib, obviously unused. WTF? Are we doing genetic sequencing here?
=> Remove unused dependencies

app/models/author.rb, app/models/author_identity.rb, db/migrate/20180224013914_remove_identity_type_from_author_identity.rb, db/schema.rb, lib/cap/authors_poller.rb, lib/science_wire/harvest_broker.rb, spec/factories/author.rb, spec/integration/harvest_broker_spec.rb, spec/lib/cap/authors_poller_spec.rb, spec/lib/science_wire/harvest_broker_spec.rb, spec/models/author_identity_spec.rb, spec/models/author_spec.rb
This field is identical throughout our production data.  That is to say, it does nothing!  Removing it was a little more cumbersome than I expected, thanks to additional scaffolding and logic that was built around it.
I took the chance to cleanup a couple other points where tests broke or had to be updated.
=> Remove identity type from author identity

app/controllers/publications_controller.rb, spec/controllers/publications_controller_spec.rb
fixes #755
to avoid issues with boolean operators in the title messing up the search...If you do a title search that includes a boolean operator, e.g. 
```GET https://sulcap-dev.stanford.edu/publications/sourcelookup?title=Nutrition and Mesenteric Issues in Pediatric Cardiac Critical Care.```
you will get a 500, which comes from the Clarivate API.  The reason is that if you don't add quotes around the title when constructing the query to clarivate it will interpret the "and" and "or" in the title incorrectly.
=> we need to quote the title search provided by the user

lib/web_of_science/process_pubmed.rb, lib/web_of_science/process_record.rb, spec/fixtures/pubmed/pubmed_record_21253920.xml, spec/lib/web_of_science/process_pubmed_spec.rb, spec/lib/web_of_science/process_record_spec.rb
fixes #758 
mimics what was done for SW before here: https://github.com/sul-dlss/sul_pub/blob/master/app/models/publication.rb#L277-L286
Notes:
- why are there two methods that do this?  do we know?  can we eliminate one?
=> add pmcid to pub_hash when available from pubmed

lib/web_of_science/map_names.rb, spec/lib/web_of_science/map_names_spec.rb
fixes #762 
* add name key to author block, which mimics what we are returning for SW records, this helps the Profiles team
* parse some WoS records that return first and middle names in the first name field to separate them correctly
* adds more specific tests for name parsing
=> Add :name key to author block to mimic what is in SW records

lib/web_of_science/map_names.rb, spec/lib/web_of_science/map_names_spec.rb
found a couple more issues after deploying the new WOS name parsing code:
* anonymous records only have a display_name / full_name attribute and no last_name attribute; to match what is happening with medline records; let's just use one of those if we can't find the last_name
* anonymous records don't have a first_name attribute which was blowing up on the gsub!; guard against this
=> handle a couple more edge cases for WOS names parsing

lib/web_of_science/harvester.rb
Example output was:
```
I, [2018-03-06T16:45:40.230009 #10247]  INFO -- : WebOfScience::Harvester - author 17853 -  - 1 UIDs for search
```
This collapses the empty `-  -`
=> Remove double-hyphen composition of log message

Gemfile, Gemfile.lock
We need to backfill a dependency (or drop ruby 2.3)
See: https://travis-ci.org/sul-dlss/sul_pub/jobs/349199941#L980
And: https://github.com/sul-dlss/sul_pub/pull/763
=> Unblock CiteProc upgrade

app/api/sul_bib/authorship_api.rb, app/models/web_of_science_source_record.rb, lib/web_of_science/identifiers.rb, lib/web_of_science/process_records.rb, spec/lib/web_of_science/process_records_spec.rb
Because there are hundreds of lines of untested code and some hamstringing complexity even building fixtures, the level of confidence I have that these tests reflect our real scenario is lower than I'd like.  But they reflect it more closely than **no tests**.
My specific outstanding question is about the *timing* of pubmed additions.  The tests inject PMID ahead of time, but the actual `process_records` code only does `pubmed_additions` as the last step
(which has been true since its beginning). I suspect that is too late for the indirect matching query we need to work.
=> Tests for matching_publication and non-wos indirect matches

config/schedule.rb
Connected to #195
Extracted from #478 so that we can delay merging this until the WOS harvesting system works.
=> Harvest schedule switched over to WebOfScience

Gemfile.lock, lib/pubmed_harvester.rb, spec/lib/pubmed_harvester_spec.rb
=> do not throw an exception when a pmid cannot be found in a search

app/models/pubmed_source_record.rb, spec/models/pubmed_source_record_spec.rb
Allow author entries previously filtered as "malformed".  If the entry doesn't declare itself invalid, it is valid by default. Otherwise, citations get built w/o any author data at all.
Fixes #814
Exclusion was introduced in 0c2059423336fd5dace0c8b586f39a007fe04557
=> Pubmed author parsing when ValidYN missing

config/settings.yml, lib/cap/authors_poller.rb, lib/tasks/wos.rake, lib/web_of_science/query_author.rb, spec/lib/cap/authors_poller_spec.rb
also:
* cleanup some logging
* add default timeframes to settings
* use timeframes when harvesting updated or new authors in cap author poller
fixes #841
fixes #842
=> timeframes for updated/new author harvests and setting that determines if authors poller runs harvests on changed authors

lib/web_of_science/retriever.rb
The inaccessibility of these complex request hashes complicates reproducibility of upstream errors.
Here the `retrieve_message` is just broken out into its own method, simplifying `retrieve_batch`.
=> Break out a private method to aid debugging, clarity

config/settings.yml, script/batch_wos_harvest.rb
If you use "nil" in settings, it gets set as a string.  On the other hand, "null" gets set correctly as the actual value nil, which we need in this case.  If you don't do this correctly, the API tries to send the string "nil" as symbolicTimeSpan to the WoS API instead of leaving off the parameter (which it does in the case of the value nil).  Sending "nil" causes an error in the API.
Also, updates to logging and add CSV output for batch harvest script for easier reporting to CAP after the run.
=> Fix issue with settings (nil should be null so it isn't set as a string)

config/settings.yml, lib/tasks/wos.rake, lib/web_of_science/harvester.rb
it be be shorter than the updated authors timeframe that results from the authors poller
also, log the options passed to the harvest method so you can see what timeframe was used when looking at the logs
=> switch regular harvest timeframe update to something different

Gemfile, Gemfile.lock
It's no longer needed since we aren't using therubyracer
=> Remove libv8

app/models/publication.rb
current production bug: https://app.honeybadger.io/projects/50046/faults/39602176#notice-summary
* sciencewire should *not* be in the path when looking up by and adding pubs by pmid
* short circuit a couple places where sw records are fetched, just in case that codepath is exercised somewhere else
we should also allocate some time time to review and merge #850
=> remove sciencewire lookup when adding by pmid

config/settings.yml
for update harvests triggered by the cap author poller detecting changes to a user profile
this was requested by Tina based on issues with a user who updated their profile and had pubs going back more than 10 years that were being missed
as this lookback window is only triggered for users who update their profiles detected by the cap authors poller, it should not have a big impact on performance (as this is a small number each night)
=> use "all time" as the lookback window 

lib/tasks/cleanup.rake
give a cap_profile_id, remove any contributions between the two dates when we started harvesting from WoS and stopped using first initial by default
will be used for cleanup of very specific authors with common last names who likely have lots of false positives on their profile (see #856)
=> rake task that will remove all new contributions for a given author between specific dates

app/models/author.rb, spec/models/author_identity_spec.rb
Found a couple issues during smoke testing of #1014 on the server...
- fix bug where a duped primary identity that was dropped was still being considered as a change (it was showing up as a nil in the array when being compared)
- fix bug where middle name was using the wrong key in the import settings and wasn't being set
- added some tests to catch these two scenarios
- have `mirror_author_identities` return true or false to indicate if it did anything and check this in tests ... otherwise it could return false even if it did work (which seems odd)
- other test refactoring
- override 'reload' method on author model to be sure it correctly resets the object's `alt_identities_changed` state (since it may need to be recomputed)
- fix a couple typos in method names (e.g. `_identites_` --> …
=> Author identity change detection fixes

app/controllers/authors_controller.rb, app/jobs/author_harvest_job.rb, config/schedule.rb, fixtures/vcr_cassettes/Cap_AuthorsPoller/_do_harvest/adds_separate_timeframes_for_harvests_for_new_and_updated_authors.yml, lib/all_sources/harvester.rb, lib/cap/authors_poller.rb, lib/pubmed/harvester.rb, lib/tasks/harvest.rake, lib/tasks/pubmed.rake, lib/tasks/wos.rake, lib/web_of_science/harvester.rb, spec/controllers/authors_controller_spec.rb, spec/integration/author_harvest_spec.rb, spec/jobs/author_harvest_job_spec.rb, spec/lib/all_sources/harvester_spec.rb, spec/lib/cap/authors_poller_spec.rb
- create a new harvester class subclassed from the base class that runs `process_author` for both WoS and Pubmed ...  running through the main `harvest_all` loop in the harvest base class only once for both sources will improve efficiency since we only query and iterate through all authors once (as opposed to querying and iterating over all others once for WoS and once for Pubmed for all authors)
- refactor the cap author poller class to take advantage of this new class instead of calling each source harvester separately
- create new rake tasks for harvesting authors for both sources
- update the cron jobs used in `schedule.rb` to use this new rake task 
- update the `author_harvest_job` class to use the new all sources class
- remove the 'harvest-alternate-names' parameter from the …
=> harvest all sources for better efficiency

app/jobs/author_harvest_job.rb, config/settings.yml, lib/all_sources.rb, lib/all_sources/harvester.rb, lib/cap/authors_poller.rb, lib/harvester/base.rb, lib/pubmed/harvester.rb, lib/tasks/harvest.rake, lib/web_of_science/harvester.rb
otherwise all sources info gets logged into default rails logger which is very noisy
also, this makes the all_sources harvester analogous to the WoS and Pubmed harvester in the way it is called.
also move log_info method to the base harvester class to avoid duplication
=> log all_sources harvesting into own log file

app/controllers/application_controller.rb, app/controllers/authors_controller.rb, app/controllers/authorships_controller.rb, app/controllers/publications_controller.rb
- two API calls convereted from grape to rails were incorrectly responding with content-type:text/plain instead of application/json causing a production issue with profiles
- don't need to protect from forgery for API only controllers (causing warnings in logs)
=> fix issue with our content-type response being incorrect

app/models/author.rb, spec/factories/publication.rb, spec/models/author_spec.rb
fixes #1052 
When creating new publications, the `Author#assign_pub` method doesn't correctly update the pub_hash due to the save calls being inside the `find_or_create_by` contribution block.  I have confirmed this on my laptop manually by testing the Pubmed harvesting code with the change in this PR (it creates the authorship block in the pub_hash correctly) and without this change (it fails to add authorship just like in prod).
This isn't a problem with WoS harvesting since the creation of new publications occurs in a different point in the code and doesn't rely on the `Author#assign_pub` method:
https://github.com/sul-dlss/sul_pub/blob/master/lib/web_of_science/process_records.rb#L93-L108
=> saving the pub should come outside the find_or_create_by block

app/models/author.rb, spec/models/author_spec.rb
When a PMID returned from our harvesting does not actually return a valid publication when we query on that ID (possibly bad data from pubmed), we don't need to throw an exception, but should instead continue with processing that author's publications.
fixes #1054
=> do not throw an exception when attempting to assign a blank publication

app/models/publication.rb, lib/tasks/cleanup.rake
- proposed cleanup task for bad harvest (run per author)
- log the pub ids we deleted so we can provide to profiles team
- destroy dependent models when we delete a publication (which is very rare and only happens in remediations like this, but if we don't destroy the associated WebOfScienceSourceRecord for example, mysql will throw a unique key constraint violation)
see https://github.com/sul-dlss/sul_pub/issues/1057#issuecomment-492480310 for logic
=> cleanup task to remove pubs and contribs harvested after a date

app/models/publication.rb, config/settings.yml, lib/all_sources/harvester.rb, lib/pubmed/harvester.rb, lib/tasks/cleanup.rake, spec/jobs/author_harvest_job_spec.rb, spec/lib/all_sources/harvester_spec.rb, spec/lib/cap/authors_poller_spec.rb
- allow Pubmed harvesting to be disabled with a setting flag (default to true, override in specific environment as needed)
- when searching for existing pubmed pubs via pmid, search pmid column in publication model directly first to improve performance and ensure we find pubs that may not have the associated publication_identifiers values (legacy pubs)
- small tweak to remediation task to store pmids we are processing before starting to delete them in case something timesout in the middle and crashes
- remove now unused sciencewire enabled flag
If accepted and deployed, we should temporarily override the new `PUBMED.harvest_enabled` option and set to `false` in both -prod and -stage settings.yml on https://github.com/sul-dlss/shared_configs until we can find why pubmed harvests produced …
=> pubmed harvest disable option; tweak to search by pmid in pub model first

lib/cap/authors_poller.rb
i noticed the CAP API doesn't return more than 100 records per page, so setting the number bigger has no effect...may as well reflect reality in our code
=> set page size of cap API to reflect reality

app/models/author.rb, spec/models/author_spec.rb
=> do not save publications if not needed when assigning a publication

lib/pubmed/query_author.rb, lib/web_of_science/query_author.rb, spec/lib/pubmed/query_author_spec.rb
=> require at least one letter in the first name when generating queries

lib/notification_manager.rb
note in the rails logs that some exceptions were not making it to honeybadger, e.g. when a StandardError was raised, and it doesn't define `backtrace`
=> there is not always an exception that includes a backtrace

lib/tasks/cleanup.rake
we need to cleanup publications regardless of visibility state (as long as they are new)
=> cleanup rake task should ignore visibility

config/deploy/cap-dev-a.rb, config/deploy/cap-uat.rb
Based on the new VMs created here: https://github.com/sul-dlss/operations-tasks/issues/2061
Will be used by the Profiles team for testing their Oracle upgrade against while we maintain the current stack of VMs.  Later we can pull down these two instances/targets and use these new ones instead: `sul-pub-cap-dev` and `sul-pub-cap-qa`
=> add new deploy targets for Profiles team to test against

.rubocop_todo.yml, config/settings.yml, lib/harvester/base.rb, lib/pubmed/harvester.rb, lib/pubmed/query_author.rb, lib/web_of_science/harvester.rb, lib/web_of_science/query_author.rb, spec/factories/author.rb, spec/lib/pubmed/harvester_spec.rb, spec/lib/pubmed/query_author_spec.rb, spec/lib/web_of_science/harvester_spec.rb, spec/lib/web_of_science/query_author_spec.rb
fixes #1149 and #1150
Basically we want to guard against invalid queries when harvesting so we don't create too many publications.
This PR also adds a guard against too many publications for WoS harvesting the same way we currently guard against too many publications for pubmed harvesting (just in case we are missing other edge cases that would generate too many publications).
Basically, look at the name query for any given authors, and if's blank call it invalid, and then skip over the author when harvesting.
It also adds a new exception class for harvesting errors so its easier to see what the actual exception is in HB (previously an error from harvesting was reported as "StandardError" and you had to dig down into the "context" to see what actually was being reported, which is easy to …
=> Fix issue with first names; add better exception for HB

Gemfile, Gemfile.lock
mysql2 0.5.3 is not currently compatible with some of our servers centos/ruby combos
it fails the build on our jenkins box ... this pins to less than 0.5.3 as recommended in #software-developers channel
n/a
If so, please confirm change was tested on stage and/or test added to sul-dlss/infrastructure-integration-test.
n/a
=> pin mysql2 to version that works on our servers

.travis.yml
Planning to upgrade to ruby 2.7.1 on the new CentOS servers, add 2.7.1 as a test target
n/a
If so, please confirm change was tested on stage and/or test added to sul-dlss/infrastructure-integration-test.
n/a
=> add ruby 2.7.1 to travis

.rubocop_todo.yml, app/controllers/publications_controller.rb, app/models/publication.rb, config/settings.yml, spec/controllers/publications_controller_spec.rb, spec/factories/publication.rb, spec/models/publication_spec.rb
Fixes #1184 
Some users cannot update their manual publications because our guard cause was looking at identifiers in the record instead of the provenance.  We later allowed model record level identifiers to be added to a publication, which was confusing our logic about which publications could be updated (and refusing to allow a legit manual publication to be updated).
Also discovered that the tests related to updating manual publications were not working as we expected.  We thought we were using a POST to generate a publication before updating it, but this was in fact not actually happening, and that POST was returning a 406, but our tests just happened to be crafted in a way that it worked anyway.  I changed the tests to use a factory to setup the test data instead of a POST within the …
=> check for manual publication before updating instead of ids

lib/smci_report.rb, spec/fixtures/reports/input.csv, spec/lib/smci_report_spec.rb
Update the custom report 
1. to allow for searching for non-Profiles authors by Orcid in addition to by name
2. to allow for overriding the symbolic timespan per author by adding a column to the input csv
Unit tests and manual run
Will update wiki page if approved (https://github.com/sul-dlss/sul_pub/wiki/Common-Support-Tasks)
=> add ability to search for authors by orcid and override timespan

config/deploy.rb, config/deploy/cap-dev-a.rb, config/deploy/cap-dev.rb, config/deploy/cap-uat.rb, config/deploy/prod.rb, config/deploy/qa.rb, config/deploy/stage.rb
Add links to server deploy environment wiki pages instead of embedding specific comments in the deploy files themselves
=> add links to wiki page with info on deploy environments

lib/smci_report.rb, spec/lib/smci_report_spec.rb
Small change to the custom rake task we are using for research intelligence report to add the ORCID to the output of report (so we can tell when we have run a search with an ORCID vs name search)
Localhost
=> add orcid to export of custom rake task report

config/deploy/cap-dev-a.rb, config/deploy/cap-dev.rb, config/deploy/cap-uat.rb, config/deploy/qa.rb, config/schedule.rb
~~HOLD for green light from Profiles team~~  green light received
Now that the new Profiles servers are online, we need to switch over the cron jobs to use the new Profiles servers.
Later, we will decommission the no longer needed servers and then we can remove the extra deploy targets as well (work in #1245)
Full checklist for the Profiles upgrade work in https://github.com/sul-dlss/operations-tasks/issues/2512
Notes:
- the current host name of the new dev server is `cap-dev-a` but will be referred to with the name `cap-dev` in the roles capistrano files since we once we decommission the old `cap-dev`, `cap-dev-a` will be accessible as `cap-dev`
=> start cron jobs on new qa and dev servers and stop on old

lib/agent/author_name.rb, spec/lib/agent/author_name_spec.rb
Found another unused method (only called from a unit test)
```
$ git grep text_search_query
lib/agent/author_name.rb:    def text_search_query
spec/lib/agent/author_name_spec.rb:  describe '#text_search_query' do
spec/lib/agent/author_name_spec.rb:        expect(all_names.text_search_query).to eq '"abc" or "def" or "qrs" or "xyz"'
```
=> remove another unused method

.rubocop.yml, app/controllers/authorships_controller.rb, app/controllers/publications_controller.rb, app/models/author.rb, app/models/publication.rb, app/models/pubmed_source_record.rb, app/models/web_of_science_source_record.rb, lib/agent/author_address.rb, lib/bibtex_identifiers.rb, lib/bibtex_ingester.rb, lib/cap/authors_poller.rb, lib/cap/client.rb, lib/cap/profile_id_rewriter.rb, lib/csl/cap_mapper.rb, lib/csl/role_mapper.rb, lib/harvester/base.rb, lib/pubmed/client.rb, lib/pubmed/fetcher.rb, lib/pubmed/harvester.rb, lib/web_of_science/harvester.rb, lib/web_of_science/identifiers.rb, lib/web_of_science/map_names.rb, lib/web_of_science/map_pub_hash.rb, lib/web_of_science/map_publisher.rb, lib/web_of_science/process_pubmed.rb, lib/web_of_science/process_records.rb, lib/web_of_science/query_author.rb, lib/web_of_science/retriever.rb
* Existing settings were too restrictive for typical coding practice.
* To be consistent with dor-services-app.
Note that these were all autocorrect changes.
Unit
.rubocop.yml
=> Loosened rubocop defaults.

app/models/author.rb, db/migrate/20210511164010_add_cap_visibility_to_authors.rb, db/migrate/20210512190856_add_index_to_authors_cap_visibility.rb, db/schema.rb, spec/models/author_spec.rb
=> add authors.cap_visibility to schema, populate from retrieved CAP authorship data

Gemfile, Gemfile.lock, app/models/publication.rb, app/models/pubmed_source_record.rb, app/validators/publication_validator.rb, lib/bibtex_ingester.rb, lib/pub_hash_validator.rb, lib/tasks/sul.rake, pub_hash_schema.yml, spec/controllers/publications_controller_spec.rb, spec/factories/publication.rb, spec/lib/bibtex_ingester_spec.rb, spec/lib/pub_hash_validator_spec.rb, spec/lib/pubmed/fetcher_spec.rb, spec/lib/web_of_science/process_records_spec.rb, spec/models/publication_identifier_spec.rb, spec/models/publication_spec.rb, spec/models/pubmed_source_record_spec.rb
pub_hash is a critical data structure, but is neither documented or validated. This is bad and will make ORCID mapping more difficult.
Unit
`pub_hash_schema.yml`
=> Document / validate pub_hash

config/initializers/okcomputer.rb, config/settings.yml, lib/orcid.rb, spec/lib/mais_spec.rb, spec/lib/orcid_spec.rb
fixes #1262
bonus copypasta fix for `spec/lib/mais_spec.rb` test description
we discussed after standup this morning, and people were OK with the VCR approach used in this PR, but i'm happy to switch to the pattern used for the `Mais` check if that's preferable (i.e. more explicitly mocking the `client.fetch_works` call/result -- i hadn't looked closely at `mais_spec.rb` until after that discussion). 
unit tests
added a setting for test orcid ID for the new check
=> ORCID API OKComputer check

.rubocop.yml, fixtures/vcr_cassettes/Orcid_Client/_add_work/adds_work.yml, fixtures/vcr_cassettes/Orcid_Client/_add_work/adds_work_again.yml, lib/orcid/client.rb, spec/lib/orcid/client_spec.rb
closes #1258
API support will be needed to add SUL-PUB publications to ORCID for researchers.
Unit
NA
=> Adds support for adding new work to Orcid.

config/deploy.rb
To ensure we always have latest shared configs
=> update shared configs on deploy

lib/csl/bibtex_mapper.rb, lib/csl/role_mapper.rb
small follow on to #1317
maybe the better thing to do would be to reassess whether the code that's commented in this PR is still needed, but for now, this at least makes the comments less confusing.
unit tests
comment only update
=> update comments that reference a now deleted class

.gitignore, README.md
a bit more clarity in instructions and protection in .gitignore re: accidentally committing secrets in the course of testing
* i created empty `production.yml` and `config/settings/production.yml` files, and they both stopped showing up in `git status` output once i made the `.gitignore` change.
* proof-reading 🙂 
README, .gitignore
=> .gitignore and README touchups re: VCR cassette generation

app/models/author.rb, spec/models/author_spec.rb
Fixes #1324 -- ensure when we save an ORCID to the database, it is valid.  This will prevent future problems when we try to use the ORCID for syncing/searching
The only process that updates the ORCID right now is `Mais::UpdateAuthorsOrcid#update`.  This validation will cause that call to fail and generate an HB alert if for some reason it gets an invalid ORCID back from MAIS.
New unit tests.
=> validate orcidid when saving to author model

.rubocop_todo.yml, pub_hash_schema.yml, spec/controllers/publications_controller_spec.rb
closes #1331
CAP submitting an application was resulting in an error due to validation.
NA
pub_hash_schema.yml
=> Changes pub_hash validation to support publications submitted by CAP.

pub_hash_schema.yml
closes #1333
To allow CAP to submit identifiers with null urls.
NA
pub_hash_schema.yml
=> Allows identifier url to be null.

fixtures/vcr_cassettes/Mais_Client/_fetch_orcid_user/raises.yml, fixtures/vcr_cassettes/Mais_Client/_fetch_orcid_user/retrieves_user.yml, fixtures/vcr_cassettes/Mais_Client/_fetch_orcid_users/retrieves_users.yml, lib/mais/client.rb, spec/lib/mais/client_spec.rb, spec/spec_helper.rb
Fixes #1322 - add a method to fetch a single user from MAIS API
Also, adjusts the vcr cassettes to use new auto privacy filter for URLs.
New tests
=> add a method to fetch a single user from MAIS

app/validators/publication_validator.rb, spec/models/publication_spec.rb
Experiment to alert HB instead of failing validation on pub_hash schema validation errors (to prevent user errors)
Updated tests
=> do not fail validation on pub_hash_schema, but alert HB instead

app/models/sciencewire_source_record.rb, spec/models/sciencewire_source_record_spec.rb
closes #1337
The DOI belongs to the publication, not the journal.
Unit
NA
=> Stop adding DOI to journal for sciencewire.

config/schedule.rb
Fixes #1348 -- note we are deliberately leaving this schedule off in production until we are complete with testing
=> enable cron schedule for orcid pushing in dev and uat

config/schedule.rb
Both cap-dev and uat are connected to the Sandbox ORCID and the UAT MaIS APIs (this is the one that returns Stanford users who have connected their sunet with ORCID).  Even though our cap-dev and qa servers each have their own databases, the author information is very similar and will be the same for users who have connected their SUNET with their ORCID (since there is only one uat API for that and both our dev and uat environment connect to it).  If we run the cron job to push ORCID works from both cap-dev and uat, we will be doing exactly the same thing twice.  Let's just setup the cron job in uat to push to ORCID once.
=> we only need push to orcid in one environment

config/schedule.rb
Fixes #1296 - turn on orcid push rake task in cron
=> turn on orcid push in production

lib/orcid/pub_identifier_mapper.rb, spec/lib/orcid/pub_identifier_mapper_spec.rb
closes #1368
So that work can be successfully submitted to ORCID.
Unit
NA
=> Ignore bad URLs.

lib/orcid/pub_mapper.rb, spec/lib/orcid/pub_mapper_spec.rb
closes #1367
So that work can be successfully submitted to ORCID.
Unit
NA
=> Strips whitespace from year.

app/models/publication.rb, app/models/pubmed_source_record.rb, spec/factories/pubmed_source_records.rb, spec/fixtures/pubmed/pubmed_record_23388678.xml, spec/models/publication_spec.rb, spec/models/pubmed_source_record_spec.rb
Fixes #1378 -- some older pubmed data has the year in a different location in the XML than we were looking for, which was causing it be missing from our data structure (pub_hash), which was then preventing us from creating the citation correctly.  We should look for it in other places in the XML too.
Also, we should be able to rebuild the pub_hash for anything with a provenance of pubmed, even if it happens to have a `wos_uid` in the record, this allows for that.
New test added, existing tests passing.
=> look for year in pubmed data in alternate locations

config/database.yml, docker-compose.yml
It makes development setup easier.
=> Add a docker-compose file for starting the database in development mode

.gitignore, spec/spec_helper.rb
So that we can run with --only-failures
=> Persist rspec state

lib/orcid/pub_mapper.rb, spec/lib/orcid/pub_mapper_spec.rb
Fixes #1383 - long abstracts need to be truncated when pushing to ORCID to fit their Works data model
Note: this is the publication we will want to try and push again when deployed, publication_id = 797885, cap_profile_id = 247934, sunet_id = ajdawes
```
p=Publication.find(797885)
p.pub_hash[:abstract].size
=> 5139
[6] pry(main)> p.contributions
=> [#<Contribution:0x00000000072a4890
id: 1577149,
author_id: 142648,
cap_profile_id: 247934,
publication_id: 797885,
status: "approved",
featured: false,
visibility: "public",
created_at: Fri, 06 Nov 2020 12:26:52 UTC +00:00,
updated_at: Sat, 07 Nov 2020 12:13:36 UTC +00:00,
orcid_put_code: nil>]
p.contributions.first.author
=> #<Author:0x0000000007093e70
id: 142648,
cap_profile_id: 247934,
sunetid: 'ajdawes',
....
```
We can re-run the works …
=> truncate long abstracts when mapping to orcid

config/schedule.rb
Stakeholder request to try increasing the frequency of push to ORCID.  Examined the log files and noted that the job currently takes about 20 minutes to run, so switching from every 3 days to every 2 days seems low risk.  Also, allow the QA job to just run weekly -- it doesn't need to be as frequent now that testing is mostly done.
=> modify frequency of orcid pushes and make less frequent in qa

lib/orcid/add_works.rb, lib/orcid/client.rb, spec/lib/orcid/add_works_spec.rb, spec/lib/orcid/client_spec.rb
Fixes #1401 - do not alert HB if the user has revoked their ORCID token (we do not get notified about this, and it is an expected error that we cannot do anything about currently)
Needs a new test
=> log warnings for errors; do not alert HB on invalid token

config/routes.rb
There is no "new" publication method, so it doesn't need a route.
=> there is no new publication method, remove route

lib/orcid/pub_author_mapper.rb, spec/lib/orcid/pub_mapper_spec.rb
ORCID allows a maximum of 150 characters in the author field name.  Let's truncate when mapping just in case we end up with a longer name in our name (which should be very rare).
Here is the HB alert that triggered it (though in this case, it this turned out to be a wonky data we generated):  https://app.honeybadger.io/projects/50046/faults/81826301 
Added a new test
=> truncate long author names when mapping to orcid

lib/orcid/identifier_type_mapper.rb, lib/orcid/pub_identifier_mapper.rb, spec/lib/orcid/pub_identifier_mapper_spec.rb
Fixes #1418 - older sciencewire publications do not have WosUIDs in the pub_hash, which is needed for pushing to ORCID.  But for older sciencewire publications, the WosUID is the same as the WosItemId (which we do have), we just need to add a prefix.
So when mapping identifiers for ORCID, let's allow this to happen.  No changes to existing data or data model, it all happens during the mapping only when sending to ORCID.
I also added a few comments to the orcid identifier mapping class to better explain what is happening.
Added new tests.
=> sciencewire provenance should map wositemid to wosuid for orcid

.circleci/config.yml, Gemfile, Gemfile.lock
Update to ruby 3.0.3
~~Note: I had to update the mysql2 gem locally to a version that the gemfile says is not currently supported on the VM, else I got errors like this:~~
~~`expected ActiveRecord::RecordNotUnique, got #<ActiveRecord::StatementInvalid: TypeError: no implicit conversion of Hash into String>`~~
~~We need to see if mysql2 0.5.3 will work on the VMs.~~ seems to install fine on both ruby 2 and ruby 3 on the vms
Locally.  Testing on CI now
=> update to ruby 3.0.3

spec/lib/web_of_science/wsdl.rb
=> remove unnec requires from a spec

app/models/pubmed_source_record.rb, spec/fixtures/pubmed/pubmed_record_10000166.xml, spec/models/pubmed_source_record_spec.rb
Fixes #1441 (upcoming request from Profiles):  if available, we should map dates from PubmedSource Records into the same YYYY-MM-DD format as we do for WoS and ORCID records
Notes:
- refactored how the year (currently done in our code) is extracted so we can use the same type of code for the month/year
- could add some more Pubmed fixtures to test some more permutations of date locations/formats to be parsed
- once done, we will need to go back and rebuild the pubhash for Pubmed sourced records if we want to the date added
There is a rake task for rebuilding Pubmed pub hashes from a previous remediation, but it starts with cap_profile_ids: see https://github.com/sul-dlss/sul_pub/blob/main/lib/tasks/pubmed.rake#L7  In this case, we may want to do *all* Pubmed sourced publications (or all …
=> Parse dates from Pubmed records into pub_hash

Gemfile, Gemfile.lock, config/database.yml, lib/web_of_science/process_pubmed.rb
We do not need mysql installed locally just to run in development/test mode.  Also, installing the mysql2 gem can be a challenge to install on a laptop due to dependencies.  This moves the mysql2 gem so it is only used in production, and allows sqlite3 to be used for dev/test.  
Since mysql defaults to case insensitive text searches, and sqllite3 does not, I made one small change to the code to ensure the tests continue to run successfully with sqlite3.
All environments deploy in production mode, so will continue to use mysql.
Test suite, and tried deploying to cap-dev to ensure it still deploys cleanly.
=> replace mysql2 gem with sqllite3 in dev/test

lib/tasks/sul.rake
Fixes #1365 - we will be doing some custom reporting to compare WoS vs Dimensions harvesting, and need a specific publication output report for our current harvesting mechanism.  This creates a rake from the commands I had been running manually in the rails console. 
Important note:  since only WoS publications are output, you may get less publications output than the min specified.
On uat and localhost.
Updated the wiki page with documentation: https://github.com/sul-dlss/sul_pub/wiki/Useful-console-commands-(harvest,-WoS,-Pubmed,-others)
=> Add a new reporting rake task to be used for dimensions analysis

config/database.yml, db/migrate/20160412224434_create_author_identities.rb, db/migrate/20210520185112_create_orcid_source_records.rb
If you run migrations on a brand new blank database, you will hit a couple failures.  One seems to be change in syntax, the other uses a datatype that is only applicable to MySQL.  These changes are needed to get them to run correctly and work with sqlite3.  They also work with mysql (I tested locally).  
Also, I added in some comments into the database.yml file in case you want to use mysql locally.
Running migrations from a blank database on sqlite3 and mysql (on laptop)
=> adjust db migrations to work with sqlite3

app/models/pubmed_source_record.rb, spec/models/pubmed_source_record_spec.rb
Temporarily roll-back pubmed date parsing (https://github.com/sul-dlss/sul_pub/pull/1442) so we can troubleshoot with Profiles team.  See discussion in #sul-cap-collab slack channel
I think we can need to do the fix described in #1469
Existing tests
=> temporarily disable pubmed date mapping

app/models/pubmed_source_record.rb, fixtures/vcr_cassettes/PubmedSourceRecord/_pubmed_update/does_not_update_the_source_data_field_if_no_pubmed_record_is_found.yml, fixtures/vcr_cassettes/PubmedSourceRecord/_pubmed_update/updates_the_source_data_field.yml, spec/models/pubmed_source_record_spec.rb
Fix for #1469 - when parsing dates from Pubmed, we need to be sure to pick the month and day from the same part of the XML structure, still going in the preferred order.  We still return the first match, even if it's only the month (and even if a month-day combo is found later in one of less preferred locations).  This is because the places to look in the XML (the xpaths) are set in order of "best date to use".  
The problem was discovered when the Profiles team updated all of their publications on -dev (where I had back-filled with the current date mapping code) and started hitting exceptions on publications with bad dates (e.g. PMID:11096574, SulPubId:8787 for example, where we had sent a date of 2019-02-30).
This makes the needed changes and re-enables the date parsing for Pubmed …
=> [HOLD] pick month and day from same part of xml

lib/tasks/sul.rake
The rake task for exporting publications for analysis picks random authors, but it's possible it will pick the same author twice if they are picked twice randomly.  This has it pick a new random number to avoid dupes.
on uat
=> avoid duping random authors when exporting

app/models/pubmed_source_record.rb, fixtures/vcr_cassettes/PubmedSourceRecord/_pubmed_update/does_not_update_the_source_data_field_if_no_pubmed_record_is_found.yml, fixtures/vcr_cassettes/PubmedSourceRecord/_pubmed_update/updates_the_source_data_field.yml, spec/models/pubmed_source_record_spec.rb
~~HOLD for now pending testing and confirmation from Profiles team.~~
Fixes #1469 
This gets us back to the original PR #1470, which was inadvertently merged before ready and was thus reverted.  That PR was approved and has code comments if you want to look at it.  Note that PR #1470 (and thus this PR as well) fixes bug #1469, which resulted from work done in #1442.
The code change is for parsing of dates from Pubmed records.  We are holding to verify in -dev and -uat with Profiles before releasing to prod.
Once this is merged and deployed, you will want to backfill dates, as described in this ticket: #1475
=> Pick month and day from same part of xml

.rubocop.yml, lib/csl/role_mapper.rb, lib/mais/client.rb, lib/orcid/identifier_type_mapper.rb, lib/orcid/pub_author_mapper.rb, lib/orcid/pub_identifier_mapper.rb, lib/orcid/pub_mapper.rb, lib/orcid/work_mapper.rb, spec/models/pubmed_source_record_spec.rb
To enforce consistency between 'return nil' and 'return'.
=> Autocorrect Style/ReturnNil cop

.circleci/config.yml, db/migrate/20220405041748_contributions_not_null.rb, db/schema.rb
To deal with data issues highlighted in #1477 
Just add a database constraint to prevent nulls from being created (it will throw an exception if we try to do this).
~~HOLD Until the existing nulls are dealt with in the production database.~~ Data deleted in #1477
~~Not sure we really need to do this, since we really should never have a nil publication_id in a contribution (though we somehow did in this case) and it is bad data.   Perhaps it's better to know by getting an exception so we can cleanup the bad data?~~
Existing tests
=> prevent bad data from being created in contributions

lib/orcid/pub_identifier_mapper.rb, spec/lib/orcid/pub_identifier_mapper_spec.rb
We apparently have nils in our identifier part of the pub_hash, this prevents an exception from occurring when mapping to ORCID.  See https://app.honeybadger.io/projects/50046/faults/84755970
Updated test to include a nil
=> deal with nils in our identifier pub_hash when mapping to ORCID

lib/orcid/pub_author_mapper.rb, spec/lib/orcid/pub_author_mapper_spec.rb, spec/lib/orcid/pub_mapper_spec.rb
Fixes #1478 
The response from the ORCID API is a bit opaque as to which field is the problem, but I suspect it is the blank name we are sending to ORCID.  See #1478 comments for the investigation.
Note that is error is from a manually entered publication where the user sent us a blank author and we just blindly send it to ORCID.  I suspect the error coming from ORCID is a rejection of this blank author value.  This PR just drops any blank authors when mapping to the ORCID JSON.
Once merged, we can try and push this publication again to confirm it makes it this time.
Added new tests.
=> do not map blank names when sending publications to ORCID

lib/tasks/sul.rake
This rake task can take a while to run (like 20 mins) and will increase in time the more users we are reporting on; this gives us some output telling us where we are in the iteration.
Tested in UAT.
=> add output when running sunet integration task

lib/smci_report.rb
Allow all publications (not just new and approved) to be exported (we still have the status in a column so rejected ones can still be removed if needed).
In production
=> allow the smci report to export all publications, not just approved

lib/tasks/sul.rake
It can be useful to re-run the dimensions analysis report using the same authors as last time instead of a random set.  This allows that option to be set by using the last output as an input (so we can use the same author ids) when running the report (and switches to env variables for inputs to the rake task facilitate this).  Just a rake task so no impact on other code.
UAT server
Will need to update the bottom of the wiki here with the new run format: https://github.com/sul-dlss/sul_pub/wiki/Useful-console-commands-(ORCID,-MaIS)#how-many-publications-were-added-with-the-orcid-push-from-profiles
=> allow the dimensions report to be run with same authors

lib/orcid/pub_mapper.rb, spec/lib/orcid/pub_mapper_spec.rb
Fixes #1496 - ORCID API has a limit on the size of a title field
I could not locate the actual field limit in the ORCID docs and don't see it in the error message, but this error was triggered with a 22,522 character title length.  I am truncating after 500 characters, which seems more than sufficient for a title. 
Added a new test
=> truncate large titles when posting to ORCID API

lib/web_of_science/client.rb
To better deal with this HB error: https://app.honeybadger.io/projects/50046/faults/79809428
Tested on qa.  Seems fine
=> Catch and retry WoS queries if session expires

lib/web_of_science/process_records.rb, spec/lib/web_of_science/process_records_spec.rb
Fixes #1502 (and #1501) -- basically if an exception occurs due to a failed external API call, our current code will log the exception via HB, but then return a data structure to the caller which will then trigger a second HB exception (which is not obvious that is is connected to the first).  This just returns an appropriate data structure to the caller so it won't trigger a secondary exception.
Added a new test.
=> do not need to throw two exceptions for same problem

spec/lib/orcid/pub_mapper_spec.rb
We generate a random string for this spec, and sometimes it is not exactly 160, but it is really only important that is bigger than 150 so we can verify it truncates to 150.
Existing tests
=> make this spec less flaky

lib/smci_report.rb
Our mapped data in the pub hash may not be perfect, and our current report code will throw a null exception in some cases.  Using dig to find values in the hash prevents this.
Ran report with this proposed change.
=> Prevent null exception in smci report

Gemfile, Gemfile.lock
v2 of the oauth2 gem seems to be causing issues getting a token for the MaIS API....the previous version of the gem works on localhost for me
see https://app.honeybadger.io/projects/50046/faults/86280516
relevant part of the code that uses this gem: https://github.com/sul-dlss/sul_pub/blob/main/lib/mais/client.rb#L94-L99
will create a separate ticket to figure out why and how we can upgrade to the v2: #1521
Localhost, verified in UAT/QA
=> pin oauth2 gem

Gemfile, Gemfile.lock, lib/mais/client.rb
Fixes #1521 - updating oauth2 gem to v2 has some breaking changes as noted in https://github.com/oauth-xx/oauth2/blob/master/CHANGELOG.md#changed
We need to set the `:auth_scheme` which changed it's default.  This lets us unpin and go to v2 of the gem
Localhost, should also verified in qa/uat
=> fix oauth2 gem settings so we can upgrade to v2

app/models/publication.rb, spec/models/publication_spec.rb
Rebuilding the pub_hash from source data is sometimes helpful if we need to do some data correction after harvesting has been done.  This is not something that is done in the production code automatically, but we have rake tasks that allow this to happen.  Use cases are (1) we discover a bug in our code that maps source data to the pub_hash, and we need to remediate previously harvested data, (2) a single record is updated at the source and we'd like to update our mapped data.
Up until now, Web of Science records cannot be rebuilt in the code as easily as other source records, even though it is absolutely possible.  
1. This adds the ability to do this by calling the same method that we can call for Pubmed or Sciencewire source records.
2. It uses a better check of the record provenance …
=> allow rebuilding of pub_hash for wos records

.gitignore, lib/pubmed/map_pub_hash.rb
Based on some questions around article publication dates in Pubmed records, I double-checked the search for dates and the order in which we search for them. I believe the current ordering is still valid and correct despite the one example shown below, but I updated the code documentation so that the ordering of links in the code comment reflect the order in which we search for dates and just added a bit more text.
Existing tests
=> additional comments around pubmed date searching

lib/smci_report.rb, lib/tasks/sul.rake
The SMCI report benefits from exporting specific date ranges (instead of just after a specific date)
See also #1505 for the same changes to a different report.
UAT
=> add ability to search for date ranges in smci report

lib/pubmed/query_author.rb, spec/factories/author.rb, spec/lib/pubmed/query_author_spec.rb
Code changes for #1546 
- if an author has a name that includes "Or", "And", or "Not" (case insensitive, either first or last), that name will be ignored when constructing the query ... this means a user could in theory have a second "alternate identity" name that is valid, and we would still use it
- if there are no valid names available, the entire query will be marked as invalid and thus not run, producing no results
- while I was making this change, I extended our existing check for invalid names (currently only first name must have at least one character) to ensure the last name also has to have at least one valid character (eg. a last name of blank or null will also be marked as an invalid name)
- reorganize spec to put all of the tests related to the `valid?` method in a describe …
=> look for invalid names for pubmed queries

spec/lib/pubmed/query_author_spec.rb
A particular spec is flaky depending on how factories generate author_identities (due to sequences in the factory).  This makes it not matter but just inspecting the value of the factory object generated.
Localhost spec
=> make test not dependent on order of factory generation

lib/tasks/sul.rake
1. When running an export of publications, it seems like we sometimes have mesh headings with blank names; which will crash the export script unless we guard against it.
2. Change the expected input column for sunetid so it matches the related authors export task.
Updated/added documentation to the wiki here: https://github.com/sul-dlss/sul_pub/wiki/ORCID-and-Publication-Reports
Localhost
=> mesh headings sometimes have no values

lib/tasks/sul.rake
1. We sometimes need to export list of publications in specific time ranges (instead of just "since" a specific date until today).  This adds that capability to two of the rake tasks that export publications.
2. The rake task that exports publication for all authors and all statuses was changed to export some more metadata (such as identifiers and publication status) to make it more useful during analysis.
Ran on UAT
Updated this wiki page: https://github.com/sul-dlss/sul_pub/wiki/ORCID-and-Publication-Reports
=> changes to publication export reports

README.md, config/schedule.rb, config/settings.yml
Fixes #1564 
Note: I don't think we need check ins for any environment other than production and QA (there are also cron jobs that run in dev, but don't warrant a checkin)
Also need shared_configs PRs:
- https://github.com/sul-dlss/shared_configs/pull/1898 (prod)
- https://github.com/sul-dlss/shared_configs/pull/1899 (qa)
=> add HB checkins for cron jobs

config/schedule.rb
Follow on from #1580 which was missing something in the schedule.rb file after HB checkins were added
=> fix schedule.rb file

lib/tasks/sul.rake
In order to run some new reports for OA analysis, we need to:
(1) Be able to filter publications exported to only specific publication years
(2) Be able to filter exported publications to only include approved publications
(3) Be able to export publications for all authors
This PR:
(1) Adds a new rake task to dump all authors in the database to CSV.  This can then be used an an import to the existing rake task.
(2) Modifies the publication export rake task to allow filtering by publication year and publication status.
Ran on QA to verify it works as intended.
=> allow exported pubs to be filtered; export all authors

lib/tasks/sul.rake
Exporting user rake task for reporting purposes, and some users have an ORCID but no sunet.  Not sure why or how this happened, but I still need to export the data and to gather stats from the ORCID integration, we need a SUNET, so we will skip users with a blank sunet.
Ran in production
=> skip users with blank sunet in rake task report

config/settings.yml, fixtures/vcr_cassettes/Cap_Client/_working_/returns_true_when_it_can_fetch_author_data.yml, lib/cap/client.rb
The CAP health check is currently failing because the hard-coded `cap_profile_id` we currently use is returning a 404 from the CAP API (may be because that person's profile is archived).  This changes the cap_profile_id to one that is confirmed working and puts in the config in case we need to change it again.
Confirm separately with Profiles team that the 404 is expected from their API for this hardcoded profile id (4176 == https://profiles.stanford.edu/intranet/richard-lewis)
Deploy to UAT to confirm
Added code comments.
=> change the cap_profile_id for health check, add to config

lib/tasks/sul.rake
ENV variable name in the code comment example is wrong, this fixes it
=> typo in code comment about how to run rake task

config/deploy/cap-dev.rb, config/deploy/qa.rb, config/deploy/uat.rb, config/schedule.rb
This commit makes a capistrano-oriented change such that the new "QA" box is one that is more resettable (UAT is not easily resettable). It effectively special-cases the cap-uat box instead of the cap-dev-a box, which we think may be more appropriate.
N/A
=> Rejigger cap stages for cap-dev-a and cap-uat VMs

lib/tasks/sul.rake
It's helpful to also have the ORCID in the `sul:export_pubs_csv` and `sul:export_pubs_for_authors_csv` rake task output , since it can be used later to match up the data with other datasets.
Running it in prod! (shhhh)
=> Add ORCID to rake task output

config/schedule.rb
We have requests from both SoM and SUL stakeholders to get regular updates on ORCID integration counts, and we have a rake task to do this (which I run manually when I remember to for recording in https://docs.google.com/spreadsheets/d/1kT-IXWprFeR5QsPa1x297oMrx7ZWhOLMg2E2H4GZkjA/edit#gid=0 or when asked).  To make my life easier, just run it weekly via cron so when someone asks, I can go and grab the latest values, or even the last few weeks worth of values to show any delta.
Localhost
=> run weekly orcid integration stats and store in file

config/schedule.rb
A recent PR added a new cron job for a rake task with the output directed to the file, but I realized the output was still going to cron.log due to how whenever gem creates cron jobs.  This fixes it to allow this particular cron job to direct it's output to a specific file.   See https://github.com/javan/whenever/wiki/Output-redirection-aka-logging-your-cron-jobs
localhost
=> fix report output of cron job

lib/mais/update_authors_orcid.rb, lib/orcid/add_works.rb, lib/tasks/cleanup.rake
In some cases an author can have more than one row in the authors table, with one being inactive and the other being active.  This sometimes happens if the author had a previous association with Stanford and then wasn't correctly matched up when they joined Stanford again.  We have a rake task to merge authors if this happens, but even after we do this, our ORCID update task may still find the inactive author row.  This fixes the issue by ensuring we only look for authors with ORCIDs that are active.
Discovered when dealing with a support request for author with a SUNet ID of `edehaan` who wasn't seeing their publications pushed to ORCID.  It turns out it is because they have two author rows and the ones with approved publications and that is marked as active is not that was associated …
=> update correct active author orcidid

lib/tasks/cleanup.rake
Follow on from #1643 -- after more thought, realized the rake task should not blindly update the primary author's ORCID from the duped author when merging authors',  but instead only do this if the primary author doesn't have an ORCIDID set already
=> do not update primary author's orcidid if it has a value already

lib/web_of_science/xml_parser.rb
Add some extra error logging when a WoS error occurs during parsing (may be useful when dealing with #1642
=> add some extra error logging

lib/web_of_science/queries.rb, spec/lib/web_of_science/queries_spec.rb
Allow a user to request a custom batch when users the 'queries' method.  This can be useful if you only want to get the number of results and the queryID back (and not all of the results).  Used in some custom rialto queries and also could be used in later refactor to first request WOS_UIDs and then later full records in small batches (to deal with #1642)
Updated spec
=> allow a user to request custom batch sizes

Gemfile, Gemfile.lock
Error handling was breaking since a Rails method signature changed.
CI
=> Use latest honeybadger gem

lib/csl/mapper.rb, spec/factories/user_submitted_source_records.rb, spec/lib/csl/citation_spec.rb
Fixes #1651 - citation generation for certain publications was failing due to an issue with how we were generating data for the citeproc gem
Localhost and new spec
(I verified the new spec fails with expected exception without fix, and then passes with fix)
=> fix issue with certain citation rendering

fixtures/vcr_cassettes/Clarivate_RestLinksClient/_links/returns_links.yml, lib/clarivate/rest_links_client.rb, spec/lib/clarivate/rest_links_client_spec.rb
Fixes #1658 - it appears some WoS UID records can come back from the Links client with no identifier block.  This guards against that scenario and appropriately returns a blank record.
Localhost and new test which hits the API and verifies the response.
I ran the new test with and without the fix and verify it fails before with the expected exception and passes afterward.
=> allow for blank identifier blocks in the Wos Links client response

lib/tasks/sul.rake
We need to be able to export publications for all publication years with this rake task ... this rake task had a bug which was preventing this, and this fixes it.
Using the modified rake task for a report right now.
=> fix issue with pub export task

app/controllers/publications_controller.rb, spec/controllers/publications_controller_spec.rb
You can only request csv format for a single author's publications currently.  This prevents an [HB alert ](https://app.honeybadger.io/projects/50046/faults/105701954)from happening if you try to get CSV for all authors.
New spec
=> send bad request for csv format for all authors

lib/tasks/sul.rake
Some additional output when running a publication export task for reporting
=> add additional output to publication export task

Gemfile, Gemfile.lock
It doesn't seem necessary and doesn't compile on new Macs.
Unit
=> Remove unicode gem

config/deploy.rb
Also, this will break deploys when we move off of the Capistrano-OneTimeKey gem.
=> Comment out ancient settings that are no longer needed

Gemfile, Gemfile.lock, app/controllers/publications_controller.rb, lib/smci_report.rb, lib/tasks/cleanup.rake, lib/tasks/sul.rake, script/delete_missing_auths.rb, script/dup_report.rb, script/merge_duplicate_authors.rb, script/repair_mixed_auths.rb, script/title_report.rb
This dependency is moving out of stdlib in Ruby 3.4 so it must be managed by bundler.
CI
=> Add csv dependency to bundler

config/deploy/qa-temp.rb, config/deploy/uat-temp.rb
Profiles is migrating servers and needs new environments for testing against (for which the data can vary with the current environments).  See https://github.com/sul-dlss/operations-tasks/issues/3879
This allows us to deploy to these new environments.
Will remove later when not needed anymore.
=> New temporary UAT and dev environments for profiles testing

config/deploy/uat-temp.rb
New Profiles uat-temp environment is ready. This is paired with https://github.com/sul-dlss/shared_configs/pull/2273 to enable it.
I verified the new Profiles URL is responding.
Rails console
=> turn on harvesting jobs in new uat-temp environment

config/deploy/uat.rb
As Profiles team continues with their migration, they tell us we do not need to have harvesting running on UAT environment for now.  This disables it.
Eventually, servers will re-shuffled and we will renable, as shown in https://docs.google.com/document/d/14K09NJG1O6Zo8u0LfrxK5g8ADLTBZ_HzkAnEr_YAsS8/edit?tab=t.0
=> can disable harvesting on uat for now

config/deploy.rb, config/deploy/prod-temp.rb, config/deploy/qa-temp.rb, config/deploy/qa.rb, config/deploy/uat-temp.rb
See https://github.com/sul-dlss/operations-tasks/issues/3951
- We are spinning up a temporary prod environment for Profile's use.
- Add some links to related tickets in code documentation.
- Disable harvesting in uat and dev environment for now (not needed per discussion with Profiles, we will be replacing the data on these servers with the -temp counterparts at some point)
- Remove unnecessary linking of secrets.yml file for all environments (noticed when deploying to prod-temp, this comes from vault now anyway)
=> setup deploy for new prod-temp environment

app/controllers/publications_controller.rb
We don't want to be enable the user to send a massive PER parameter which would generate a massive response and potentially cause problems on the server.
=> enforce max per page on publications API

lib/csl/author_name.rb
=> Remove misleading usage of `protected` keyword

config/deploy/qa-temp.rb, config/deploy/uat-temp.rb
The production migration will result in us restoring a prod database over the qa and dev environments once complete (as noted by the Profiles team).  This means we can turn off harvesting in the temp dev and UAT environments, as these databases will soon be overwritten by prod anyway.  See https://github.com/sul-dlss/operations-tasks/issues/3952 for the upcoming plan.
=> no need for harvesting in qa and deve temp

Gemfile, Gemfile.lock
We've been seeing some strange deadlock errors during dependency updates and were wondering if they were related to the version of sqlite that is being used in the Jenkins environment.
```
Some locked specs have possibly been yanked (sqlite3-1.7.3-x86_64-linux). Ignoring them...
```
At one time we pinned sqlite back because of a Rails incompatibility issue. However that issue has since been merged. This PR lets sqlite version float again. It is only used in development (tests) and MySQL is used in production.
=> Float sqlite version

Gemfile, Gemfile.lock
We need to pin the mais-orcid-client so that the changes in the new API do not go into effect until we do the new gem release and update the codebase.
=> pin mais-orcid-client

config/deploy/prod.rb, config/deploy/qa-temp.rb, config/deploy/qa.rb, config/deploy/stage.rb, config/deploy/uat-temp.rb, config/deploy/uat.rb
This line has been a no-op since dlss-capistrano 5.2.0. Setting up the one-time key is done automatically in dlss-capistrano now.
=> Remove explicit one-time key setup

.circleci/config.yml, Gemfile, Gemfile.lock, README.md, compose.yaml, config/database.yml, db/migrate/20130703222701_change_pub_hash_to_medium_text.rb, db/migrate/20160405194617_switch_to_medium_text.rb, db/migrate/20171213201429_wos_src_record_medium_text.rb, db/migrate/20171215001732_wos_source_record_integer_pmid.rb, db/migrate/20210520185112_create_orcid_source_records.rb, db/schema.rb
Connects to #1783
Includes:
* Change DB config to use Postgres for all envs
* Remove MySQL-isms from DB migrations and allow `db:migrate` to function with Postgres underneath
* Remove unnecessary customization from CI config and use the ruby-rails-orb instead
* Add Postgres container to `docker compose`
* Reflect above changes in README
`bin/rake db:drop db:create db:migrate`
=> Switch default database from MySQL to Postgres

config/schedule.rb
Noticed the recent orcid output stats from the scheduled rake task were just empty files.  i think the syntax for redirecting standard out in whenever gem changed at some point.  Looked at documentation, adjusted code, and looked at what whenever gem will produce, and seems better now.  Tested on prod and produced output to file as expected.
Also adjusted filename production format to avoid potential shelling out issues.
See https://github.com/javan/whenever/wiki/Output-redirection-aka-logging-your-cron-jobs
=> adjust whenever syntax so standard out is written to file
